// Product Design case studies — inclusive, "you solved it" walkthroughs in Shubham's voice.
// Inspired by The Product Folks product-design category; original writing.
// Blocks: p | step{label,x} | sub{x} | note{x} | callout{label,x} | ul{items} | rice{label,rows:[{name,r,i,c,e,score}]}
window.DESIGN_CASES = [
  {
    slug: "google-home-blind", company: "Google", wordmark: "Google Home", brand: "#4285f4", readTime: "7 min read",
    title: "How would you design the Google Home Mini for blind users?",
    body: [
      { t: "p", x: "Designing for accessibility is where product empathy gets real — we're not adding a feature, we're handing someone independence. So let's design this together. I'll lay out the choices; you make the calls with me. By the end, this design is yours." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["What's the primary goal — reduce dependency on others, or speed up daily tasks?", "Which metrics matter — task completion, usage frequency, satisfaction?", "Who exactly: fully blind or partially sighted? Age 18-50, low-to-medium tech comfort.", "Do we have data on how blind users struggle with the current device?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Employed, fully-blind adults running home + work solo.", "Partially-sighted users who still rely on voice.", "Elderly blind users, less tech-confident.", "Tech-hesitant first-time smart-speaker owners."] },
      { t: "note", x: "Your turn — who has the most to gain if we nail this? Picture each one. I'd back the employed, fully-blind adult managing everything hands-free: independence here is genuinely life-changing. Agree? Then let's commit." },
      { t: "callout", label: "We're designing for", x: "The employed, fully-blind adult running their day hands-free — highest need, highest payoff." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Voice commands are complex and easy to get wrong.", "Initial setup is visual and hard to do alone.", "No tactile feedback — you can't feel whether the device heard you.", "Confusing, silent error states."] },
      { t: "note", x: "Pause — which pain would YOU fix first? Rank by how badly and how often it bites. For me one rises above the rest: no tactile feedback. Every single interaction becomes a guess. That's the one." },
      { t: "callout", label: "The pain we'll solve", x: "Lack of tactile feedback — blind users can't feel whether the device registered them." },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Tactile buttons/surfaces with distinct textures.", "Haptic + audio confirmation on every action.", "A guided audio setup tutorial.", "Customisable voice responses and feedback."] },
      { t: "step", label: "STEP 5", x: "Prioritise with RICE — your call" },
      { t: "rice", label: "Reach × Impact × Confidence ÷ Effort", rows: [
        { name: "Distinct-texture tactile buttons", r: 8, i: 9, c: 8, e: 6, score: 96 },
        { name: "Haptic + audio confirmation", r: 8, i: 8, c: 7, e: 5, score: 90 },
        { name: "Guided audio setup", r: 7, i: 7, c: 8, e: 5, score: 78 },
        { name: "Customisable voice responses", r: 6, i: 6, c: 7, e: 5, score: 50 }
      ] },
      { t: "step", label: "STEP 6", x: "Build the winner" },
      { t: "ul", items: ["Design textures that are unmistakable by touch alone.", "Place buttons for intuitive, no-look reach.", "User-test with blind individuals — not assumptions.", "Choose durable, comfortable materials for daily use.", "Integrate cleanly so the device still looks and feels premium."] },
      { t: "step", label: "STEP 7", x: "Metrics + pitfalls" },
      { t: "ul", items: ["Task-completion rate; setup success without help.", "Usage frequency; satisfaction (surveys, reviews).", "Support-ticket drop for setup/interaction.", "Pitfall: too many buttons clutter — keep textures few and truly distinct, and validate with real users."] },
      { t: "callout", label: "What you just designed", x: "A Google Home Mini that talks AND can be felt — tactile, confirmable, independent. You chose the user, the pain and the fix." },
      { t: "p", x: "See that? YOU just designed for accessibility — picked the user who needed it most, the pain that hurt most, and the highest-impact fix. That's product-design sense, and it was you driving the whole way." }
    ]
  },
  {
    slug: "fiverr-india", company: "Fiverr", wordmark: "Fiverr", brand: "#1dbf73", readTime: "6 min read",
    title: "How would you design Fiverr for India?",
    body: [
      { t: "p", x: "Localising a global product for India isn't translation — it's rethinking payments, language and trust from the ground up. Let's design it together; you'll pick the user and shape the roadmap with me." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["What's unique about India — digital access, price sensitivity, culture?", "Which service categories will be most popular here?", "Legal/regulatory issues to plan for?", "Pan-India, or start regional?", "English-only, or local languages?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Freelance professionals (design, writing, dev).", "SMB owners needing affordable services.", "Corporates wanting one-off specialists.", "Students freelancing part-time.", "Homemakers monetising their skills from home."] },
      { t: "note", x: "Your turn — which persona seeds the whole marketplace? Supply comes first: without freelancers, there's nothing to buy. I'd prioritise the Freelance Professional — including folks who pivoted to freelancing post-COVID. You with me?" },
      { t: "callout", label: "We're designing for", x: "The Freelance Professional — the supply that makes the marketplace exist." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Hard to market skills and find steady work.", "Unsure how to price for the Indian market.", "Confused by contracts, taxes, legal basics.", "Payment friction — delays, non-payment, international transfers.", "Language barrier — most platforms are English-only."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Rich profiles + AI matching for consistent work.", "India-specific pricing insights and suggested ranges.", "Legal support: basic contracts, tax guidance.", "UPI/Paytm + international-transfer support.", "Multilingual support for major Indian languages."] },
      { t: "step", label: "STEP 5", x: "Prioritise — phase it with me" },
      { t: "ul", items: ["Phase 1: solid platform — categories, clean UI, AI matching, integrated payments.", "Phase 2: market-based pricing insights + multilingual support.", "Phase 3: legal services, analytics, advanced features from feedback."] },
      { t: "note", x: "Notice the discipline — payments and matching first (the deal-breakers), niceties later. Would you sequence it differently? Defend your order; that's the real skill." },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Sign-ups (esp. freelancers).", "Engagement — bids/offers made.", "Conversion — transactions completed.", "Satisfaction (ratings/surveys); churn rate."] },
      { t: "callout", label: "What you just designed", x: "A Fiverr that speaks Indian languages, pays in UPI, prices for the local market and backs its freelancers — sequenced so the essentials ship first. Your call, start to finish." },
      { t: "p", x: "That's localisation done right — you found the persona who anchors the marketplace and built for their real, India-specific pains. Not a translation; a redesign." }
    ]
  },
  {
    slug: "mentorbridge", company: "MentorBridge", wordmark: "MentorBridge", brand: "#5b2fe0", readTime: "6 min read",
    title: "Design a networking app connecting students and professionals for career guidance in India.",
    body: [
      { t: "p", x: "Career-guidance apps live or die on one thing: do students actually connect with people who help them? Let's design it together — you'll pick who we serve first and what we build." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Which students — high-school, college, or postgrad?", "India-only, or expand later?", "Specific industries (tech, arts, business)?", "New build or an existing base?", "Online-only, or offline events too?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["High-schoolers exploring career paths.", "College students hunting internships / first jobs.", "Postgrads seeking advanced roles.", "Early professionals wanting to network.", "Mentors and HR looking for talent."] },
      { t: "note", x: "Your turn — which group has the sharpest, most solvable need right now? I'd pick college students chasing internships and entry-level jobs: high urgency, clear outcome. Lock it in?" },
      { t: "callout", label: "We're designing for", x: "College students looking for internships and entry-level jobs — urgent need, measurable win." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Unaware of what careers even exist.", "Little real-world industry exposure.", "Hard to network with professionals.", "No personalised guidance.", "Struggle to find internships matching their skills."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Career-exploration hub with pro Q&A.", "Live projects, internships, mentorship programs.", "Easy networking — DMs, groups, forums.", "AI career guidance from interests + skills.", "A dedicated job/internship portal."] },
      { t: "step", label: "STEP 5", x: "Prioritise — your ranking" },
      { t: "ul", items: ["1. Networking — the core connective tissue.", "2. Job/internship portal — the utility that retains.", "3. AI guidance — the differentiator.", "4. Career awareness — fold into the above.", "5. Industry experience — grow via partnerships later."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["User acquisition + retention.", "DAU and engagement (connections, time, features used).", "Job/internship application rate per active user."] },
      { t: "callout", label: "What you just designed", x: "A networking-first app that connects students to professionals, matches them to internships, and guides them with AI — built in the order that actually delivers connections. You chose the persona and the priorities." },
      { t: "p", x: "You just resisted the urge to build everything at once — picked the urgent persona, led with networking, and let the rest follow. That focus is exactly what makes a design ship." }
    ]
  },
  {
    slug: "gharsmart", company: "GharSmart", wordmark: "GharSmart", brand: "#ff5a3c", readTime: "6 min read",
    title: "Design a smart-home automation system tailored to Indian households.",
    body: [
      { t: "p", x: "'Smart home for India' is a trap if you copy the West — the constraints (power cuts, domestic help, budgets) are different. Let's design for the real Indian home, together." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Typical home architecture and layouts?", "Target income bracket?", "Climate conditions to design around?", "Cultural/social factors (e.g., domestic help)?", "Tech literacy + existing infra (internet, smartphones)?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Middle-class urban working professionals.", "High-income big-city business owners.", "Lower-income rural households.", "Elderly living alone or with family.", "Young adults / flatmates."] },
      { t: "note", x: "Your turn — where's the fastest-growing adoption? The urban middle class is racing into smart tech. I'd prioritise middle-class urban working professionals. Sound right to you?" },
      { t: "callout", label: "We're designing for", x: "Middle-class urban working professionals — the fastest-adopting segment." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["No time — professional life eats household management.", "High energy bills from inefficient appliance use.", "Growing urban security concerns.", "Wanting to supervise domestic help when away.", "Forgetting to switch off AC/lights when leaving."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Routine automation (schedules, auto-off).", "Energy management — cut idle draw, off-peak use.", "Security — smart locks, alarms, remote video.", "Monitoring — cameras/motion with access control.", "Voice-assistant integration for one-tap control."] },
      { t: "step", label: "STEP 5", x: "Prioritise — your call" },
      { t: "ul", items: ["1. Security (remote video, smart locks) — top anxiety.", "2. Energy management — hits the wallet.", "3. Routine automation — daily convenience.", "4. Voice control — seamless layer.", "5. Domestic-help monitoring — valuable add-on."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Engagement (how often/long used).", "Energy saved (% reduction).", "Satisfaction; retention; adoption rate."] },
      { t: "callout", label: "What you just designed", x: "A smart-home system built for Indian realities — security-first, energy-smart, help-aware — for the urban professional who has money but no time. You led every decision." },
      { t: "p", x: "You designed for the actual context, not a Silicon-Valley fantasy — power, help, security, budget. That's the difference between a demo and a product people in India actually buy." }
    ]
  },
  {
    slug: "gadgetshare", company: "GadgetShare", wordmark: "GadgetShare", brand: "#0a7d3e", readTime: "6 min read",
    title: "Design a platform that lets users rent and share smart gadgets.",
    body: [
      { t: "p", x: "Renting gadgets is really about access-over-ownership — and trust. Let's design it together; you'll pick the user whose need is sharpest." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Which gadgets — broad, or a category (smart home, wearables)?", "Audience — tech enthusiasts, general, businesses?", "Do we handle logistics, or peer-to-peer?", "Geographic focus?", "How do we guarantee gadget condition + data safety?", "Business model — subscription, pay-per-use, mix?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Tech enthusiasts wanting the latest, can't buy all.", "Budget users needing gadgets temporarily.", "Small businesses needing gear without heavy spend.", "Travellers needing portable Wi-Fi, cameras, etc."] },
      { t: "note", x: "Your turn — whose need repeats most (so they keep renting)? The tech enthusiast wants the newest thing constantly — high repeat demand. I'd start there. Your pick?" },
      { t: "callout", label: "We're designing for", x: "The Tech Enthusiast — constant appetite for the newest gadgets, high repeat rentals." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Latest gadgets cost a fortune to own.", "Devices go obsolete fast.", "Region-locked launches are hard to access.", "Data-privacy worries when renting."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Flexible subscription tiers by gadget/duration.", "Constantly refreshed inventory (manufacturer tie-ups for early access).", "Cross-region gadget requests via logistics partners.", "Rigorous data-wipe + security process; user education."] },
      { t: "step", label: "STEP 5", x: "Prioritise — Impact/Effort with me" },
      { t: "ul", items: ["High impact, low effort → start here: subscription plans + data-wipe/security.", "High impact, high effort: regular latest-gadget refresh; international procurement.", "Low impact: international logistics partners; user-education content."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Acquisition; active renters.", "Rental frequency; churn.", "Satisfaction; revenue."] },
      { t: "callout", label: "What you just designed", x: "A rent-the-latest platform with flexible plans and rock-solid data safety first — the two high-impact, low-effort wins. You picked the user and the sequence." },
      { t: "p", x: "You used Impact/Effort to avoid the trap of chasing shiny-but-hard features first. Ship the cheap high-impact wins, earn trust, then scale. Smart sequencing — all yours." }
    ]
  },
  {
    slug: "skillserve", company: "SkillServe", wordmark: "SkillServe", brand: "#5b2fe0", readTime: "6 min read",
    title: "Design a skill-based volunteering platform connecting people with NGOs in India.",
    body: [
      { t: "p", x: "A two-sided social platform only works if BOTH sides show up — but one side seeds the other. Let's design it together and find that seed." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Urban, rural, or both?", "Which skills are in scope?", "Primary language?", "Free, or a revenue model?", "Do we screen/verify NGOs and volunteer skills?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Individual volunteers (tech, design, marketing, medicine…).", "NGOs needing specific skills.", "Local social organisations.", "Sponsors/donors."] },
      { t: "note", x: "Your turn — which side must we win first? Without skilled volunteers, NGOs get nothing. Supply seeds this marketplace. I'd prioritise Individual Volunteers. Agree?" },
      { t: "callout", label: "We're designing for", x: "Individual Volunteers — the skilled supply that makes the platform useful to NGOs." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Hard to find NGOs matching their interests + skills.", "Clunky coordination with NGOs.", "Unclear time commitment and tasks.", "No recognition for contributions.", "Can't see their real impact."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Skill-based matchmaking (volunteers ↔ NGO needs).", "In-app messaging for coordination.", "Clear role descriptions + time commitments.", "Recognition — certificates, badges, references.", "Impact showcase tying work to the mission."] },
      { t: "step", label: "STEP 5", x: "Prioritise — your ranking" },
      { t: "ul", items: ["High: skill-based matchmaking (the whole point).", "High: clear role descriptions (sets expectations).", "Medium: seamless messaging; recognition system.", "Low: impact showcase (great, but later)."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Volunteer acquisition + retention.", "Matchmaking success rate.", "NGO and volunteer satisfaction scores."] },
      { t: "callout", label: "What you just designed", x: "A matchmaking-first volunteering platform with crystal-clear roles — built to win the volunteer side that seeds everything. You made the calls." },
      { t: "p", x: "You spotted the seed side of a two-sided platform and led with the feature that IS the value (matchmaking). That instinct — win supply, be clear, then delight — is pure product sense." }
    ]
  },
  {
    slug: "taxease", company: "TaxEase", wordmark: "TaxEase", brand: "#d0021b", readTime: "6 min read",
    title: "Design an app that simplifies filing income-tax returns for individuals in India.",
    body: [
      { t: "p", x: "Tax filing is stressful, error-prone and easy to get wrong — perfect territory for a product that removes fear. Let's design it together and pick who needs it most." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["How do people file today?", "Which existing apps exist — strengths/weaknesses?", "What mistakes do individuals commonly make?", "Which compliances trip people up?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Salaried employees (mostly TDS).", "Small business owners (multiple income sources).", "Freelancers (many clients, deductions).", "Elderly, less digital-comfortable."] },
      { t: "note", x: "Your turn — whose tax life is the messiest (so simplifying helps most)? Freelancers: many income streams, patchy withholding, deductible expenses. I'd prioritise them. Your pick?" },
      { t: "callout", label: "We're designing for", x: "Freelancers — the most complex tax situation, so the biggest relief." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Tracking income from many sources.", "Categorising deductible expenses.", "Confusing rules and regulations.", "Filing is slow and complex.", "Fear of mistakes → penalties/audits."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Link bank accounts to auto-track income.", "Capture + categorise expenses (OCR receipt scan).", "Plain-language tax-rules repository.", "Step-by-step guided filing UI.", "AI error-check before submission."] },
      { t: "step", label: "STEP 5", x: "Prioritise — your order" },
      { t: "ul", items: ["1. Income + expense tracking (the core pain).", "2. Guided filing UI (simplifies the act).", "3. Rules repository (stop-gap-able, so later).", "4. AI error-check (advanced value-add)."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Engagement; error rate on filings.", "Completion rate of started filings.", "Satisfaction; time saved vs. traditional filing."] },
      { t: "callout", label: "What you just designed", x: "A tax app that auto-tracks a freelancer's income and expenses, walks them through filing, and catches errors before they cost money. You chose the persona and the build order." },
      { t: "p", x: "You picked the messiest user (freelancers) and led with the boring-but-essential core (tracking) before the flashy AI. That restraint is what makes a genuinely useful product — and it was your call." }
    ]
  },
  {
    slug: "shakti", company: "Shakti", wordmark: "Shakti", brand: "#e5006e", readTime: "6 min read",
    title: "Design an app that empowers Indian women with resources, networks and mentorship.",
    body: [
      { t: "p", x: "'Empower Indian women' is huge and vague — real design starts by getting specific about WHO and WHAT. Let's narrow it together and build something that truly helps." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Which women — age, education, urban/rural, working?", "Which resources — jobs, education, health, mentorship?", "Any focus industries for mentorship?", "Digital-literacy level?", "Budget?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Young urban professional (mid-20s–early-30s, employed).", "Rural woman (less digital, income/education/health needs).", "Student (career/scholarship guidance).", "Homemaker (income-from-home, new skills)."] },
      { t: "note", x: "Your turn — who can benefit immediately (so we prove value fast)? The young urban professional is already digital and in the workforce. I'd start there, then expand. Agree?" },
      { t: "callout", label: "We're designing for", x: "The young urban professional — digital, employed, ready to benefit day one." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Hard to find mentorship + growth resources.", "Unreliable/unverified opportunities.", "Limited networking with peers and mentors.", "Knowledge gaps about women-centric initiatives.", "Data-privacy and personal-safety concerns."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Curated, verified resources + mentors.", "Simple, safe, user-friendly interface.", "In-app community to network and share.", "Regular updates on new opportunities.", "Strong data-security + safety measures; educational content."] },
      { t: "step", label: "STEP 5", x: "Prioritise — your order" },
      { t: "ul", items: ["1. Secure, easy interface (the foundation).", "2. Curated resources + mentors.", "3. Networking community.", "4. Opportunity updates.", "5. Educational modules."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Acquisition + retention; engagement.", "Feedback/ratings.", "Conversion — resources used, mentors connected."] },
      { t: "callout", label: "What you just designed", x: "A safe, curated, community-driven app that connects young professional women to verified mentors and opportunities — trust and safety built in from step one. Your decisions throughout." },
      { t: "p", x: "You turned a vague, well-meaning brief into a specific, buildable product by choosing one persona and putting safety first. Narrowing down IS the design work — and you did it." }
    ]
  },
  {
    slug: "campusconnect", company: "CampusConnect", wordmark: "CampusConnect", brand: "#ff5a3c", readTime: "6 min read",
    title: "Design a social app connecting Indian college students across universities.",
    body: [
      { t: "p", x: "Cross-university connection is powerful but uneven — some students are far more cut off than others. Let's design for the ones who need the bridge most, together." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Target age group?", "One field of study, or all?", "National, or start with regions/universities?", "Academic collaboration only, or clubs/sports/culture too?", "Existing competitors? Tech constraints? Accessibility needs?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Freshers adapting to college life.", "Seniors mentoring juniors.", "Students in remote locations.", "Active club/society members.", "Research-oriented collaborators."] },
      { t: "note", x: "Your turn — who's most isolated (so a bridge helps most)? Students in remote locations face distance, limited exposure, patchy connectivity. I'd prioritise them. Your call?" },
      { t: "callout", label: "We're designing for", x: "Students from remote locations — most isolated, most to gain from connection." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Limited exposure to diverse communities/ideas.", "Distance makes networking hard.", "Poor internet connectivity.", "Left out of inter-university activities."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["'Discover' feed of trending topics + events across universities.", "AI-based matching + interest groups.", "Low-bandwidth optimisation + offline mode.", "Virtual events, webinars, competitions."] },
      { t: "step", label: "STEP 5", x: "Prioritise — Impact/Effort with me" },
      { t: "ul", items: ["High impact / high effort: AI matching (data + training).", "High impact / medium effort: 'Discover' feed.", "High impact / low effort → quick win: virtual events.", "Medium: low-bandwidth optimisation."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Activation (onboard + first interaction).", "Retention; engagement (DAU, time, posts).", "NPS; meaningful-connection rate."] },
      { t: "callout", label: "What you just designed", x: "A cross-university app that reaches isolated students — quick-win virtual events now, AI matching and a Discover feed as it grows, all tuned for low bandwidth. You picked the persona and the sequence." },
      { t: "p", x: "You designed for the student the others forget, and used Impact/Effort to ship a quick win before the heavy AI lift. That's empathy plus pragmatism — exactly your call." }
    ]
  },
  {
    slug: "scholarpath", company: "ScholarPath", wordmark: "ScholarPath", brand: "#2874f0", readTime: "6 min read",
    title: "Design a platform to discover and apply for scholarships and grants in India.",
    body: [
      { t: "p", x: "Scholarships are life-changing but buried under noise and scams. Designing this well means cutting through both. Let's build it together and pick who we help first." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Target age group?", "Indian scholarships only, or international too?", "All education levels, or one?", "Just applications, or tracking/reminders/suggestions too?", "Whole country or a region? Academic only, or sports/arts too?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["High-school students heading to undergrad.", "Undergrads seeking postgrad scholarships.", "Postgrads seeking research grants.", "Parents finding aid for their child.", "Counsellors assisting students."] },
      { t: "note", x: "Your turn — who's at the start of the journey, most confused, most helpable? High-school students, just beginning to navigate all this. I'd prioritise them. Agree?" },
      { t: "callout", label: "We're designing for", x: "High-school students — beginning the scholarship journey, needing the most guidance." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Unaware of what scholarships exist.", "Information overload online.", "Confusing application process, docs, deadlines.", "Prone to scams/misinformation.", "Hard to track applications and status."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Personalised dashboard matching their profile.", "Search + filters (type, level, field).", "Step-by-step application guidance.", "Rigorous validation of every listing (anti-scam).", "Application tracking + status."] },
      { t: "step", label: "STEP 5", x: "Prioritise — your ranking" },
      { t: "ul", items: ["High: personalised dashboard; search/filters; rigorous validation (trust).", "Medium: step-by-step guidance; application tracking."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Active users; engagement (searches, applications).", "Conversion — visitors who apply.", "Satisfaction; retention."] },
      { t: "callout", label: "What you just designed", x: "A scholarship platform that matches students to real, verified opportunities and guides them through applying — trust and personalisation first. You led the whole way." },
      { t: "p", x: "You made anti-scam validation a top priority, not an afterthought — because for this user, one scam destroys trust forever. Reading that stakes-check is exactly the judgment being tested." }
    ]
  },
  {
    slug: "fitlocal", company: "FitLocal", wordmark: "FitLocal", brand: "#fc8019", readTime: "6 min read",
    title: "Design a platform connecting fitness enthusiasts with local trainers.",
    body: [
      { t: "p", x: "Fitness is a marketplace AND a motivation problem. Let's design it together — you'll pick the user and prioritise with RICE." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Urban only, or rural too?", "All fitness types (yoga, gym, Zumba), or specific?", "Individual trainers only, or gyms/studios?", "Age groups — kids, adults, seniors?", "Budget constraints for hiring?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Fitness enthusiasts seeking a routine.", "Certified trainers offering sessions.", "Gym owners providing trainers."] },
      { t: "note", x: "Your turn — who drives demand? Busy urban professionals want to stay fit but can't make it to a gym. I'd prioritise them. Your pick?" },
      { t: "callout", label: "We're designing for", x: "Busy urban professionals who want fitness but struggle to find the time." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Hard to find a reliable local trainer.", "Can't fit workouts into a packed schedule.", "No personalisation to their level/goals.", "Hard to track progress.", "Low motivation training alone."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Search trainers by type, experience, reviews.", "Easy booking around their schedule.", "Personalised workout plans per client.", "Progress tracking toward goals.", "Social layer — sharing, challenges, community."] },
      { t: "step", label: "STEP 5", x: "Prioritise with RICE — your call" },
      { t: "rice", label: "Reach × Impact × Confidence ÷ Effort", rows: [
        { name: "Search + booking", r: 9, i: 9, c: 8, e: 5, score: 130 },
        { name: "Personalised workout plans", r: 8, i: 8, c: 7, e: 6, score: 75 },
        { name: "Progress tracking", r: 8, i: 7, c: 7, e: 6, score: 65 },
        { name: "Social / challenges", r: 7, i: 6, c: 6, e: 7, score: 36 }
      ] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Acquisition + retention.", "Session-booking rate vs. active users.", "Trainer-onboarding rate; satisfaction."] },
      { t: "callout", label: "What you just designed", x: "A find-and-book-a-trainer platform — search + booking first (the core job), then personalisation and progress, with social motivation later. RICE made the call obvious, and you made it." },
      { t: "p", x: "You let RICE settle the debate — search + booking dwarfs everything because it IS the core job. Motivation features are lovely, but they wait. That prioritisation discipline is all yours." }
    ]
  },
  {
    slug: "givetrace", company: "GiveTrace", wordmark: "GiveTrace", brand: "#2f9e44", readTime: "6 min read",
    title: "Design an app to donate to charities and track your impact.",
    body: [
      { t: "p", x: "People want to give — what stops them is time and trust. Design that away and giving flows. Let's build it together and pick who we serve first." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Geographic scope — global, national, local?", "All charities, or certain types?", "Monetary only, or goods/services too?", "Do we partner with charities for impact reporting?", "Any API/tech to track impact?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Busy philanthropists (high income, low time).", "Conscious consumers (want impact, modest means).", "Corporate donors (CSR + reporting).", "Casual givers (trend-driven)."] },
      { t: "note", x: "Your turn — who can give a lot but is blocked by friction? Busy philanthropists have the means; time and trust are the barriers. Remove those and giving scales. I'd start there. Agree?" },
      { t: "callout", label: "We're designing for", x: "Busy philanthropists — the means to give big, blocked only by time and trust." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["No time to research where money helps most.", "Can't track their donation's impact.", "Doubts about charity transparency/integrity.", "Hard to keep donation records for taxes."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Curated charity list by cause, rating, transparency.", "Impact tracking via charity partnerships + reports.", "Verified transparency scores (third-party audits).", "Automatic donation records + tax reports."] },
      { t: "step", label: "STEP 5", x: "Prioritise — your order" },
      { t: "ul", items: ["1. Trust + transparency (the real blocker).", "2. Research aid (curated, fast decisions).", "3. Impact tracking.", "4. Donation + tax records."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Acquisition + retention.", "Donation volume.", "Charity engagement (updates provided); satisfaction."] },
      { t: "callout", label: "What you just designed", x: "A giving app that builds trust first, makes choosing fast, then proves impact and handles tax records — for the philanthropist blocked only by time and doubt. Your calls throughout." },
      { t: "p", x: "You correctly named the real barrier — trust — and made it priority #1, not a feature buried in settings. Diagnosing the true blocker before designing is exactly the move. Well played." }
    ]
  },
  {
    slug: "wanderpack", company: "Wanderpack", wordmark: "Wanderpack", brand: "#00a7e1", readTime: "6 min read",
    title: "Design an app to book domestic travel packages in India.",
    body: [
      { t: "p", x: "Travel booking in India is fragmented and impersonal. Design a calmer, more tailored way through it. Let's build it together and pick who leads." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Target audience — all ages, or specific?", "Packaged tours only, or flights/hotels individually?", "Current solutions and their problems?", "Full-service (visa, forex), or just travel?", "What does 'simplify' mean here — fewer steps, transparency, guidance?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Middle-aged couples wanting hassle-free trips.", "Solo budget adventurers.", "Family travellers (mixed ages).", "Retirees exploring leisurely.", "Corporate travellers (fast + efficient).", "Millennials seeking offbeat experiences."] },
      { t: "note", x: "Your turn — who's most open to trying a new app (a great beachhead)? Millennials: tech-savvy, adventurous, willing to switch. I'd start with them. Your pick?" },
      { t: "callout", label: "We're designing for", x: "Millennial travellers seeking offbeat experiences — tech-savvy, willing to try a new app." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["Hard to find unique, lesser-known destinations.", "Pre-set packages don't fit their preferences.", "Opaque pricing and itineraries.", "Hard to find reliable reviews + local experiences.", "Juggling multiple apps for booking/reviews/planning."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["'Explore' feed of offbeat destinations.", "'Customise Package' — pick-and-choose elements.", "Transparent pricing with cost breakdown + opt-outs.", "Integrated user reviews and ratings.", "One unified plan-book-review platform."] },
      { t: "step", label: "STEP 5", x: "Prioritise — Impact/Feasibility with me" },
      { t: "ul", items: ["1. Customise Package — high impact, feasible.", "2. Unified platform — high impact, feasible.", "3. Transparent pricing — high impact, vendor pushback risk.", "4. Explore feed — moderate, easy.", "5. User reviews — moderate, feasible."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Downloads + active users; engagement.", "Trips planned/booked; plan→book conversion.", "NPS/ratings; revenue."] },
      { t: "callout", label: "What you just designed", x: "A travel app that lets millennials customise offbeat trips transparently, all in one place — customisation and a unified platform first. You chose the beachhead and the priorities." },
      { t: "p", x: "You picked a beachhead segment (millennials) to prove the product, then led with customisation — the thing pre-set packages can't do. Beachhead thinking is how new products get a foothold, and it was your call." }
    ]
  },
  {
    slug: "transitnow", company: "TransitNow", wordmark: "TransitNow", brand: "#5b2fe0", readTime: "6 min read",
    title: "Design an app for real-time public-transport schedules and routes.",
    body: [
      { t: "p", x: "Public transport anxiety is mostly uncertainty — 'when's it coming, and which way?' Design that uncertainty away and you change people's commute. Let's build it together." },
      { t: "step", label: "STEP 1", x: "Clarify the brief" },
      { t: "ul", items: ["Which transport — bus, train, metro, trams, bikes?", "Dense or sparse city?", "Users' tech literacy?", "Existing real-time feed to integrate, or build from scratch?", "Main objective — ridership, experience, congestion, info?", "Budget/timeline; integrations (tickets, maps)?"] },
      { t: "step", label: "STEP 2", x: "Meet the users" },
      { t: "ul", items: ["Daily commuters (rely on it, need accuracy).", "Tourists/visitors (unfamiliar, need simplicity).", "Special-needs passengers (extra assistance).", "Casual/leisure users."] },
      { t: "note", x: "Your turn — who uses it most and depends on it most? Daily commuters, twice a day, every day. Nail their experience and the app has a loyal core. I'd prioritise them. Agree?" },
      { t: "callout", label: "We're designing for", x: "Daily commuters — highest frequency, highest dependence, loyal core." },
      { t: "step", label: "STEP 3", x: "Their pain points" },
      { t: "ul", items: ["No real-time info — uncertain arrival times, missed rides.", "Inefficient route planning across the network.", "Unexpected delays/changes with no timely alert."] },
      { t: "step", label: "STEP 4", x: "Solutions on the table" },
      { t: "ul", items: ["Real-time vehicle tracking + accurate arrival predictions.", "Dynamic route planning (multi-modal).", "Proactive disruption alerts + alternative suggestions."] },
      { t: "step", label: "STEP 5", x: "Prioritise — your order" },
      { t: "ul", items: ["1. Real-time tracking — the core need.", "2. Efficient route planning — convenience + ridership.", "3. Disruption alerts — critical but complex (unpredictable + needs alternatives)."] },
      { t: "step", label: "STEP 6", x: "Metrics" },
      { t: "ul", items: ["Engagement (frequency, session length).", "Satisfaction (usefulness, reliability).", "Adoption (downloads, active users).", "Route optimisation (shorter travel times)."] },
      { t: "callout", label: "What you just designed", x: "A transit app that kills commute uncertainty — real-time tracking first, smart routing next, proactive disruption alerts as you scale. You picked the loyal-core user and the sequence." },
      { t: "p", x: "You anchored on the highest-frequency, highest-dependence user and led with the feature that removes their core anxiety. Serve your loyal core brilliantly first — that focus was entirely your decision." }
    ]
  }
];
