// Metrics case studies — full, detailed walkthroughs in Shubham's voice.
// Inspired by The Product Folks metrics category; original writing.
// Same block types as RCA: p | step{label,x} | sub{x} | note{x} | callout{label,x} | ul{items} | journey{label,steps}
window.METRICS_CASES = [
  {
    slug: "apple-steps", company: "Apple", wordmark: "Apple", brand: "#1d1d1f", readTime: "9 min read",
    title: "You launched daily-step tracking in Apple Health. What metrics prove it's a success?",
    body: [
      { t: "p", x: "Here's the trap in every metrics question: the interviewer secretly wants a firehose of numbers, and a nervous candidate obliges — thirty metrics, no spine. Don't. A great answer is a story: what is this feature FOR, what single number proves it's working, and what would I refuse to break to get there. Let's build that story for Apple's step tracker." },
      { t: "step", label: "STEP 1", x: "What is this feature really for?" },
      { t: "p", x: "The daily-steps feature quietly logs how much you move and turns it into a gentle nudge to move more — while helping Apple Health personalise its advice. So the real job isn't 'count steps.' It's 'get people genuinely moving, and coming back.' Health apps are a booming space, but the currency here is trust — this is intimate data." },
      { t: "journey", label: "User journey", steps: ["Update to the OS with step tracking", "See steps on widget / watch", "Get progress + insight nudges", "Move more", "Return tomorrow"] },
      { t: "note", x: "Write the goal on your hand before you list a single metric: this feature wins if people actually move more, keep coming back, and trust us with their data. Every metric below serves that — or it gets cut." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Weekly active users who hit their step goal (or beat their own trend). Not 'installs,' not 'steps logged' — people actually moving more, week after week. That single number captures real health value delivered." },
      { t: "step", label: "STEP 3", x: "Input metrics — the levers that move the star" },
      { t: "sub", x: "Discovery & adoption" },
      { t: "ul", items: ["% of users on the OS version that has step tracking.", "% who placed the step widget on home/lock screen or watch face.", "Adoption split by device — iPhone-only vs. Apple Watch.", "% who enabled step/progress notifications."] },
      { t: "sub", x: "Engagement" },
      { t: "ul", items: ["DAU & MAU of the feature, split by device.", "Notification open rate, by device type.", "Goal-completion rate — % hitting their daily target.", "Feature stickiness — DAU/MAU (do they keep coming back?)."] },
      { t: "sub", x: "Behaviour & satisfaction" },
      { t: "ul", items: ["Actual step-count lift for active users vs. non-users — the real proof it works.", "CSAT and Customer Effort Score on the feature.", "Qualitative: surveys, interviews, app-store reviews.", "Cohort analysis to watch behaviour evolve over time."] },
      { t: "step", label: "STEP 4", x: "Guardrails — what I refuse to break" },
      { t: "ul", items: ["Notification opt-outs / feature-disable rate (are we annoying people?).", "Battery and performance complaints.", "Privacy-trust signals and related support tickets."] },
      { t: "step", label: "STEP 5", x: "The deliberate exclusion" },
      { t: "callout", label: "What I'd NOT chase — and why", x: "Revenue and monetisation. Health data is sacred; ads or paywalls here would torch trust and hurt the very engagement that makes the app valuable. I'd explicitly de-prioritise revenue and win on trust, engagement and retention first. Naming what you WON'T measure is a senior move — it shows judgment." },
      { t: "p", x: "See the shape? One clear job → one North Star → a tidy ladder of inputs → guardrails → a brave exclusion. That's a metrics answer that sounds like a PM, not a dashboard. You can run this exact skeleton on any feature on earth." }
    ]
  },
  {
    slug: "youtube-reco", company: "YouTube", wordmark: "YouTube", brand: "#ff0000", readTime: "9 min read",
    title: "As PM for YouTube's recommendation algorithm, what metrics prove it works?",
    body: [
      { t: "p", x: "Algorithm questions feel intimidating — 'how do you even measure a recommendation engine?!' Relax. An algorithm has exactly one job: put the right thing in front of the right person at the right moment. Measure how well it does THAT, and watch for the sneaky ways it can cheat. Let's go." },
      { t: "step", label: "STEP 1", x: "What is the algorithm really for?" },
      { t: "p", x: "YouTube has 2 billion+ users and an ocean of videos. The reco engine exists to personalise — surface content you'll love, keep you watching, and help you discover new channels. Its job: relevance that leads to satisfying engagement." },
      { t: "sub", x: "The pains it's fighting" },
      { t: "ul", items: ["Overwhelm — too much choice, nothing feels findable.", "Repetition — the same videos on loop, so people disengage.", "Off-target picks — suggestions that miss, denting trust."] },
      { t: "journey", label: "The recommendation loop", steps: ["Land on home / search", "Watch → behaviour tracked", "Feedback (implicit + explicit) tunes the model", "Return to sharper picks"] },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Valued watch time — time spent watching recommended content that users actually finish or rate well. Raw watch time alone gets gamed by clickbait; 'valued' watch time ties the number to genuine satisfaction." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Relevance & engagement" },
      { t: "ul", items: ["Click-through rate on recommendations (are picks tempting?).", "Average watch time / % of video watched on recommended videos.", "Session length and videos-per-session driven by recos.", "Skip rate and 'not interested' clicks (negative signal)."] },
      { t: "sub", x: "Discovery" },
      { t: "ul", items: ["% of watch time from newly discovered channels.", "Diversity of recommendations served (are we broadening, or looping?)."] },
      { t: "sub", x: "Retention" },
      { t: "ul", items: ["Return rate — do reco-heavy users come back more?", "Long-term DAU/MAU stickiness."] },
      { t: "step", label: "STEP 4", x: "Guardrails — how a reco engine cheats" },
      { t: "ul", items: ["Clickbait ratio — high CTR but low completion = the model is tricking people.", "Filter-bubble / repetition rate — same content over and over.", "Dislike, report and 'don't recommend channel' actions.", "Regret signals — surveys asking 'was this worth your time?'"] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "The algorithm's winning when valued watch time and healthy discovery rise together, while clickbait, repetition and regret stay flat or fall. Engagement that people are glad they had — that's the bar." },
      { t: "p", x: "Any ranking or recommendation feature bows to this frame: define relevance, measure satisfying engagement, and guard against the cheap tricks that inflate the number. Master this and 'measure the algorithm' stops being scary." }
    ]
  },
  {
    slug: "zoom-breakout", company: "Zoom", wordmark: "zoom", brand: "#2d8cff", readTime: "8 min read",
    title: "You launched breakout rooms for Zoom. How would you measure success?",
    body: [
      { t: "p", x: "New collaboration feature, 'how do you measure success?' The instinct is to count how many people click it. Resist — clicks aren't value. Breakout rooms exist to make big meetings feel small and productive. Measure THAT." },
      { t: "step", label: "STEP 1", x: "What is the feature really for?" },
      { t: "p", x: "Breakout rooms let a host split a big Zoom call into smaller groups for focused discussion, then pull everyone back. The job: turn passive, one-to-many webinars into active, many-to-many collaboration — for teachers, workshops and large teams." },
      { t: "journey", label: "User journey", steps: ["Host opens a meeting", "Creates breakout rooms", "Participants split into groups", "Discuss in small groups", "Return to main room"] },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Meetings that successfully use breakout rooms and get rated productive — hosts who run breakouts and come back to run them again. It ties the feature to the real outcome: better meetings, repeatedly." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Adoption" },
      { t: "ul", items: ["% of eligible meetings (by size/type) that use breakout rooms.", "Number of hosts who've tried it at least once.", "Time-to-first-use after the feature became available."] },
      { t: "sub", x: "Engagement" },
      { t: "ul", items: ["Average time participants spend in breakout rooms.", "Participant activity inside rooms — talk time, screen shares, chat.", "Rooms per meeting and average room size."] },
      { t: "sub", x: "Retention" },
      { t: "ul", items: ["Repeat usage — % of hosts who run breakouts again within 30 days.", "Retention of the feature across a host's meetings."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Setup friction — time to create rooms; abandonment mid-setup.", "Support tickets and confusion (participants lost, can't return).", "Meeting drop-off during breakout transitions.", "Host CSAT on the feature."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = high adoption among meetings that should use it, real participation inside rooms, hosts choosing it again, and setup that doesn't frustrate. If people use it once and never again, that's a loud failure no matter how big the first number looked." },
      { t: "p", x: "For any B2B collaboration feature: measure whether it makes the core job better and gets repeated — not whether it earned a curious first click." }
    ]
  },
  {
    slug: "spotify-share", company: "Spotify", wordmark: "Spotify", brand: "#1db954", readTime: "8 min read",
    title: "You launched playlist sharing on Spotify. How would you measure success?",
    body: [
      { t: "p", x: "A sharing feature is really a growth feature in disguise. Yes it drives engagement — but the magic is that shared playlists pull in and re-activate OTHER people. So I measure engagement AND the viral loop. Here's how." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Playlist sharing lets users send their curated playlists to others. Goal: more engagement, more music discovery, a stronger community — and, quietly, a viral growth loop where a shared link brings people back to Spotify." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Incremental listening driven by shared playlists — the extra time-spent-listening that happens because a playlist was shared and opened. It captures engagement and the network effect in one number." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Adoption — discoverable and used as intended?" },
      { t: "ul", items: ["Playlists shared per user.", "Unique users sharing playlists.", "Share-completion rate (started → finished a share)."] },
      { t: "sub", x: "Growth — is usage rising, and what drives it?" },
      { t: "ul", items: ["Growth in shares over time.", "Shares by genre, mood and user segment (what content spreads?).", "Open rate on shared links, and new/reactivated users per share — the viral coefficient."] },
      { t: "sub", x: "Engagement" },
      { t: "ul", items: ["New music discoveries via shared playlists.", "Time spent listening to shared playlists.", "Likes, follows and comments on shared playlists."] },
      { t: "sub", x: "Retention" },
      { t: "ul", items: ["Retention of users who share, and of users who listen to shares."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Spammy sharing (blasting links, low open rates).", "Broken or dead shared links.", "Any dip in core listening if sharing distracts from it."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Winning = shares growing, each share pulling in real listening and sometimes a new user, and both sharers and listeners sticking around. If shares rise but nobody opens them, the loop's broken — fix discovery, not the counter." },
      { t: "p", x: "Every social/sharing feature: measure the engagement it creates AND the growth loop it powers. Miss the loop and you've undervalued the whole feature." }
    ]
  },
  {
    slug: "netflix-mylist", company: "Netflix", wordmark: "NETFLIX", brand: "#e50914", readTime: "8 min read",
    title: "What's the key metric for Netflix's 'My List' feature?",
    body: [
      { t: "p", x: "'My List' looks tiny — a save-for-later button. But its real job is huge: make sure you never run out of reasons to open Netflix. Measuring it well means measuring whether saved intent turns into watched content." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "My List lets users save shows and movies to watch later — a personal queue. Goal: kill the 'what do I watch?' friction, so people spend more time watching and feel their subscription is worth it." },
      { t: "journey", label: "User journey", steps: ["Browse content", "Add titles to My List", "Return later", "Watch from My List"] },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Watch-through rate of saved titles — the % of My List additions that actually get watched. That's the number proving intent becomes consumption, not a graveyard of good intentions." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Adoption" },
      { t: "ul", items: ["Users who use My List at least once.", "Items added to My List per user."] },
      { t: "sub", x: "Engagement" },
      { t: "ul", items: ["% of My List content eventually watched.", "Average time between adding and watching (does it actually remind them?).", "Sessions that start from My List."] },
      { t: "sub", x: "Value & monetisation" },
      { t: "ul", items: ["Session-length lift for My List users (more perceived subscription value)."] },
      { t: "sub", x: "Retention" },
      { t: "ul", items: ["Repeat usage of My List.", "Subscription retention for heavy My List users vs. others."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Overstuffed, never-watched lists (saving is not value).", "The list going stale and irrelevant over time."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = people add to My List, come back, and watch it — with longer sessions and stronger retention. A million saves that never get watched is a vanity metric wearing a nice coat." },
      { t: "p", x: "For any 'save/bookmark' feature: the metric that matters isn't saves — it's saved-things-that-get-used. Always follow intent through to action." }
    ]
  },
  {
    slug: "duolingo", company: "Duolingo", wordmark: "duolingo", brand: "#58cc02", readTime: "8 min read",
    title: "What's the key metric for Duolingo's language-learning feature?",
    body: [
      { t: "p", x: "Duolingo lives or dies on one thing: do people keep coming back long enough to actually learn? A language isn't learned in a session; it's learned in a streak. So the key metric has to capture sustained, effective practice." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "The core learning feature delivers bite-sized lessons that build a language over time through daily practice, streaks and gentle pressure. The job: get people practising consistently and actually progressing." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Weekly active learners who complete at least one lesson — sustained, real practice. Not downloads, not lessons-started: lessons finished, week after week. Learning is a habit, so the star must measure the habit." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Adoption & activation" },
      { t: "ul", items: ["Signup → first-lesson-completed rate.", "Time to first completed lesson."] },
      { t: "sub", x: "Engagement & habit" },
      { t: "ul", items: ["Lesson completion rate.", "Streak length and streak-retention.", "Sessions per week; notification opt-in and open rates.", "Daily-goal completion."] },
      { t: "sub", x: "Learning outcomes" },
      { t: "ul", items: ["Skill/level progression over time.", "Accuracy trends and review performance — are they actually learning, not just tapping?"] },
      { t: "sub", x: "Retention" },
      { t: "ul", items: ["D1 / D7 / D30 retention.", "Streak-freeze usage (fighting churn)."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Grinding without learning — high activity, flat accuracy.", "Notification fatigue and uninstalls.", "Gaming streaks with trivial lessons."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Winning = weekly learners and streaks climbing WHILE accuracy and progression hold — proof they're practising and improving, not just protecting a streak. Habit plus learning, together." },
      { t: "p", x: "For any habit product, the key metric is sustained, effective use — reps that actually move the user forward. Guard hard against activity that looks like learning but isn't." }
    ]
  },
  {
    slug: "etsy-seller", company: "Etsy", wordmark: "Etsy", brand: "#f1641e", readTime: "9 min read",
    title: "What key metrics matter for Etsy's seller platform?",
    body: [
      { t: "p", x: "A marketplace has two customers, and it's easy to obsess over buyers and forget the sellers who make the whole thing exist. For Etsy's seller platform, I'd measure the health of supply: can sellers list, get seen, and make money — happily enough to stay?" },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Etsy's seller platform lets independent makers set up shop, list products, manage orders and grow. Its job: give sellers the tools and demand to succeed — because thriving sellers create the selection buyers come for." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Active sellers making meaningful sales — sellers with recent, repeat sales above a healthy threshold. Not 'shops created': shops that actually sell. Supply health is the marketplace's heartbeat." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Onboarding & activation" },
      { t: "ul", items: ["Signup → first-listing rate.", "Time to first listing and first sale.", "Listings per seller."] },
      { t: "sub", x: "Seller success" },
      { t: "ul", items: ["Sellers' conversion rate (views → orders).", "Average revenue per active seller.", "Repeat-sale rate; order fulfillment and on-time shipping."] },
      { t: "sub", x: "Engagement with tools" },
      { t: "ul", items: ["Adoption of ads, analytics and promotions.", "Frequency of shop-management activity."] },
      { t: "sub", x: "Retention" },
      { t: "ul", items: ["Seller retention / churn.", "Reactivation of dormant shops."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Seller CSAT and support-ticket load (fees, disputes).", "Fee sensitivity — do rising fees push sellers out?", "Quality/complaint rate that could hurt buyers."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = more active sellers making real money and staying, with tools they actually use. A pile of empty shops isn't supply — it's noise." },
      { t: "p", x: "In any marketplace, measure BOTH sides. Neglect supply health and the demand you love eventually starves." }
    ]
  },
  {
    slug: "airbnb-booking", company: "Airbnb", wordmark: "airbnb", brand: "#ff5a5f", readTime: "9 min read",
    title: "What key metrics matter for Airbnb's booking system?",
    body: [
      { t: "p", x: "The booking system is where Airbnb makes or breaks its promise. Everything upstream — search, listings, photos — exists to get someone to this moment. So I measure whether intent converts into a confirmed, happy booking, without friction or fear." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Airbnb's booking flow turns a browsing guest into a confirmed reservation — dates, payment, host confirmation. Its job: convert intent into trusted, completed bookings for both guest and host." },
      { t: "journey", label: "User journey", steps: ["Search stays", "View listing", "Check dates & price", "Request / Book", "Pay", "Host confirms", "Trip"] },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Completed bookings — searches that end in a confirmed, paid, non-cancelled stay. It captures the whole funnel's real output, not just search volume or clicks." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Funnel conversion" },
      { t: "ul", items: ["Search → listing-view rate.", "Listing-view → booking-request rate.", "Request → confirmed-booking rate.", "Overall look-to-book conversion."] },
      { t: "sub", x: "Friction & speed" },
      { t: "ul", items: ["Time to book; steps to complete.", "Payment success/failure rate.", "Instant-book adoption vs. request-to-book."] },
      { t: "sub", x: "Trust & quality" },
      { t: "ul", items: ["Cancellation rate (guest and host).", "Post-stay ratings and rebooking rate."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Host-side cancellations (they kill trust).", "Payment errors and drop-off.", "Support tickets during booking.", "Price/fee transparency complaints."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = a higher share of searches becoming confirmed, low-cancellation, well-rated stays — booked fast and paid smoothly. A rise in bookings that then cancel is a mirage; watch the guardrails." },
      { t: "p", x: "For any transactional flow: North Star is the completed, quality transaction; inputs are the funnel steps; guardrails are the trust and payment risks that can inflate a hollow number." }
    ]
  },
  {
    slug: "tinder-swipe", company: "Tinder", wordmark: "tinder", brand: "#fe3c72", readTime: "8 min read",
    title: "What's the single most important metric for Tinder's swipe feature? Why?",
    body: [
      { t: "p", x: "'What's the ONE most important metric?' is a discipline test — can you commit? For Tinder's swipe, I won't hedge with a list. I'll pick one, defend it, and name what I considered and rejected. That's the whole skill here." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Swiping is Tinder's core loop — a quick yes/no on profiles, and a match when two people both say yes. The job isn't swipes; it's creating meaningful connections that keep people using the app." },
      { t: "step", label: "STEP 2", x: "Weighing the candidates" },
      { t: "ul", items: ["Swipes per session — pure activity; easily inflated, says nothing about value.", "Match rate — closer, but a match with no conversation is empty.", "Conversations started per user — warmer; real human contact.", "Matches that turn into conversations — the moment the product actually delivers."] },
      { t: "callout", label: "The most important metric", x: "Matches that turn into conversations, per active user. That's the instant Tinder delivers on its promise — two people connect and actually talk. Everything else is a step toward it or a vanity proxy for it." },
      { t: "step", label: "STEP 3", x: "Why this one" },
      { t: "ul", items: ["It sits at the true value moment — connection, not just activity.", "It's hard to game — you can't fake a two-sided conversation.", "It predicts retention — people who match and talk come back."] },
      { t: "step", label: "STEP 4", x: "Supporting inputs I'd still watch" },
      { t: "ul", items: ["Swipe volume and right-swipe rate (top of funnel).", "Match rate.", "Message-reply rate.", "D7 / D30 retention."] },
      { t: "step", label: "STEP 5", x: "Guardrails" },
      { t: "ul", items: ["Swipe fatigue and burnout.", "Spam and creepy-behaviour reports (quality of connections).", "Gender/segment imbalance in matches."] },
      { t: "p", x: "Picking one metric isn't reckless — it's leadership. Name the value moment, choose the metric closest to it, defend it, and keep a couple of inputs and guardrails in your back pocket." }
    ]
  },
  {
    slug: "slack-message", company: "Slack", wordmark: "slack", brand: "#611f69", readTime: "8 min read",
    title: "What's the single most important metric for Slack's message feature? Why?",
    body: [
      { t: "p", x: "Slack's whole existence is one behaviour: teams talking. So the 'most important metric' question is really 'what proves a team has genuinely adopted Slack as their home?' I'll pick one and defend it hard." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Messaging is Slack's core — channels and DMs that replace internal email and become a team's nerve centre. The job: become the place a team actually works together, every day." },
      { t: "step", label: "STEP 2", x: "Weighing the candidates" },
      { t: "ul", items: ["Messages sent — activity, but a noisy team isn't the same as a working one.", "DAU — good, but doesn't capture depth of adoption.", "Active channels per team — hints at real workflow.", "Teams past a message threshold — the classic proxy for 'this team is hooked.'"] },
      { t: "callout", label: "The most important metric", x: "Weekly active teams where a critical mass of members send and read messages regularly — team-level engagement, not individual pings. Slack succeeds when a TEAM adopts it, not when one person is chatty." },
      { t: "step", label: "STEP 3", x: "Why this one" },
      { t: "ul", items: ["Slack's value is a network effect inside a team — it only works if enough of the team is on it.", "Team engagement predicts retention and paid conversion far better than raw message counts.", "It resists gaming — you can't fake a whole team's habit."] },
      { t: "step", label: "STEP 4", x: "Supporting inputs I'd still watch" },
      { t: "ul", items: ["Messages per active user.", "Active channels per team.", "% of team members active weekly.", "Integrations connected (workflow depth)."] },
      { t: "step", label: "STEP 5", x: "Guardrails" },
      { t: "ul", items: ["Notification overload and mute rates.", "Message volume without reading (noise, not value).", "Team churn after trial."] },
      { t: "p", x: "For collaboration tools, the value lives at the TEAM level. Pick the metric that proves group adoption and you'll never be fooled by one loud user." }
    ]
  },
  {
    slug: "postmates", company: "Postmates", wordmark: "Postmates", brand: "#1a1712", readTime: "8 min read",
    title: "What's the single most important metric for Postmates' delivery service? Why?",
    body: [
      { t: "p", x: "On-demand delivery is a promise: your thing, fast, reliably. For Postmates, the 'most important metric' has to capture whether that promise is kept — because break it once and the customer's gone. Let me commit to one." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Postmates delivers food and goods on demand. The job: fast, reliable delivery people trust enough to order again and again." },
      { t: "step", label: "STEP 2", x: "Weighing the candidates" },
      { t: "ul", items: ["Total deliveries — demand, but says nothing about quality.", "Delivery time — crucial, but not the whole promise.", "On-time delivery rate — closer to the promise.", "Repeat order rate — proof of trust, but a lagging outcome."] },
      { t: "callout", label: "The most important metric", x: "Successful on-time deliveries as a share of orders — the promise, kept. It's the tightest measure of whether Postmates does the one thing it exists to do, and it directly drives the repeat behaviour everything depends on." },
      { t: "step", label: "STEP 3", x: "Why this one" },
      { t: "ul", items: ["It's the core value moment — the thing arrives, fast, as promised.", "It predicts retention — reliability earns the next order.", "It spans the whole operation — supply, routing, couriers — forcing end-to-end health."] },
      { t: "step", label: "STEP 4", x: "Supporting inputs I'd still watch" },
      { t: "ul", items: ["Average delivery time and its variance.", "Order-to-courier assignment time.", "Cancellation and failed-delivery rate.", "Courier availability vs. demand."] },
      { t: "step", label: "STEP 5", x: "Guardrails" },
      { t: "ul", items: ["Courier earnings and retention (the supply side).", "Customer CSAT and complaint rate.", "Order accuracy."] },
      { t: "p", x: "For any service business, the north star is the promise kept, measured tightly. Nail reliability and repeat business follows; miss it and no amount of marketing saves you." }
    ]
  },
  {
    slug: "uber-rides", company: "Uber", wordmark: "Uber", brand: "#1a1712", readTime: "9 min read",
    title: "As PM for Uber's ride-sharing feature, what KPIs would you focus on?",
    body: [
      { t: "p", x: "'What KPIs would you focus on?' for a two-sided marketplace like Uber is a balancing act — riders, drivers and the business all have to win at once. I'll organise the KPIs so they tell one coherent story, not thirty scattered numbers." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Uber's promise: transportation as reliable as running water — tap, and a ride appears. The job: match rider demand with driver supply, fast and affordably, at scale." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Completed rides — total successful trips. It's the heartbeat that reflects healthy demand, healthy supply, and a working match between them." },
      { t: "step", label: "STEP 3", x: "Input KPIs — organised by who they serve" },
      { t: "sub", x: "Demand & growth" },
      { t: "ul", items: ["MAU and new-user acquisition.", "App-open frequency; rides per rider.", "Market penetration by region."] },
      { t: "sub", x: "Supply (drivers)" },
      { t: "ul", items: ["Active drivers and driver retention.", "Driver ratings and earnings.", "Supply-demand balance and wait times."] },
      { t: "sub", x: "Marketplace efficiency" },
      { t: "ul", items: ["Request → completed-ride rate.", "ETA and pickup time.", "Surge frequency (a symptom of imbalance)."] },
      { t: "sub", x: "Business" },
      { t: "ul", items: ["Gross bookings and revenue.", "Rider CLV and repeat usage.", "Price elasticity."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Safety incidents and response time (non-negotiable).", "Cancellation rate (rider and driver).", "Support resolution rate and time.", "Driver churn from low earnings."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = completed rides growing on the back of balanced supply and demand, healthy driver earnings, tight ETAs and rock-solid safety — not growth bought by burning drivers or cutting safety corners." },
      { t: "p", x: "For a marketplace, group your KPIs by stakeholder and let a single North Star (the completed transaction) sit on top. That's how you show you can hold the whole system in your head." }
    ]
  },
  {
    slug: "linkedin-jobs", company: "LinkedIn", wordmark: "Linkedin", brand: "#0a66c2", readTime: "8 min read",
    title: "As PM for LinkedIn's job-posting feature, what KPIs would you focus on?",
    body: [
      { t: "p", x: "LinkedIn's job board is also a two-sided marketplace: employers posting, seekers applying. The KPIs have to prove both sides get value — a posting that draws great applicants, and a seeker who finds the right role." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "The job-posting feature lets employers list roles and reach LinkedIn's professional network, and lets seekers discover and apply. The job: quality matches between roles and candidates." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Successful hires facilitated — or its leading proxy, quality applications per posting that progress. The marketplace works when postings find good candidates and candidates find good roles." },
      { t: "step", label: "STEP 3", x: "Input KPIs" },
      { t: "sub", x: "Employer side" },
      { t: "ul", items: ["Job postings created; repeat-posting rate.", "Applications per posting; applicant quality/fit.", "Time-to-fill a role."] },
      { t: "sub", x: "Seeker side" },
      { t: "ul", items: ["Job-view → apply conversion.", "Application-completion rate.", "Relevance of recommended jobs (apply rate on recos)."] },
      { t: "sub", x: "Engagement" },
      { t: "ul", items: ["Seeker return rate to the jobs tab.", "Saved jobs and job-alert opt-ins."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Spam / low-quality or fake postings.", "Ghosted applicants (applications with no response).", "Employer and seeker CSAT."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = postings drawing relevant applicants who progress to hires, and seekers finding roles worth applying to — both sides leaving satisfied. Volume without matches is a busy graveyard." },
      { t: "p", x: "Two-sided again: measure value delivered to BOTH employer and seeker, with the successful match as the north star. Spam and ghosting are the guardrails that keep the number honest." }
    ]
  },
  {
    slug: "snapchat-stories", company: "Snapchat", wordmark: "Snapchat", brand: "#1a1712", readTime: "8 min read",
    title: "As PM for Snapchat's Stories feature, what KPIs would you focus on?",
    body: [
      { t: "p", x: "Stories are about ephemeral, everyday sharing among friends. So the KPIs must capture a healthy two-way loop: people posting stories AND friends watching them. A feed of posters with no viewers (or vice versa) is dead." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Snapchat Stories let users post photos/videos that friends can view for 24 hours. The job: keep friends casually sharing and consuming each other's moments, daily." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Daily users who both post AND view stories — the healthy creation-consumption loop. Snapchat wins when the same people keep feeding and watching the feed." },
      { t: "step", label: "STEP 3", x: "Input KPIs" },
      { t: "sub", x: "Creation" },
      { t: "ul", items: ["% of DAU posting a story.", "Stories posted per creator; posting frequency."] },
      { t: "sub", x: "Consumption" },
      { t: "ul", items: ["Story views per user; completion rate (watch to the end).", "Unique stories viewed per session."] },
      { t: "sub", x: "Interaction" },
      { t: "ul", items: ["Replies and reactions to stories.", "Screenshots and shares of stories."] },
      { t: "sub", x: "Retention" },
      { t: "ul", items: ["DAU/MAU stickiness.", "Return rate of active posters and viewers."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Creation/consumption imbalance (too many lurkers, or too few viewers).", "Drop-off mid-story (boring content or too many ads).", "Report and block rate."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = a growing base of people who both post and watch daily, with rising completion and interaction. A spike in posts that nobody watches is a warning, not a win." },
      { t: "p", x: "For social feeds, always measure BOTH sides of the loop — creation and consumption — plus the balance between them. That balance is the real health signal." }
    ]
  },
  {
    slug: "amazon-prime", company: "Amazon Prime", wordmark: "prime", brand: "#00a8e1", readTime: "9 min read",
    title: "As PM for Amazon Prime, what metrics would you use to evaluate performance?",
    body: [
      { t: "p", x: "Prime isn't a feature — it's a membership flywheel: fast shipping + video + music + deals, all bundled to make you loyal and spend more. Measuring it means measuring the flywheel, not any single perk. Let's zoom out properly." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Amazon Prime bundles free fast shipping, Prime Video, Music and exclusive deals into a paid membership. The job: deepen loyalty and spend, so members buy more, stay longer, and rarely shop elsewhere." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Member retention paired with spend — the renewal rate of members combined with their purchase frequency. Prime wins when members keep paying AND keep buying, year over year." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Membership health" },
      { t: "ul", items: ["Sign-ups and free-trial → paid conversion.", "Annual renewal rate.", "Churn and reactivation."] },
      { t: "sub", x: "Engagement across benefits" },
      { t: "ul", items: ["Order frequency and average order value, members vs. non-members.", "Prime Video/Music usage among members.", "Benefit breadth — how many perks a member uses (multi-benefit members churn less)."] },
      { t: "sub", x: "Economics" },
      { t: "ul", items: ["Member CLV vs. acquisition + benefit cost.", "Incremental spend attributable to Prime."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Shipping-speed reliability (the core promise).", "Cost-to-serve per member.", "Benefit fatigue / underused perks.", "Member CSAT."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = members renewing and spending more, using multiple benefits, at a healthy margin. A surge of trial sign-ups that don't convert or renew is a leaky flywheel, not a win." },
      { t: "p", x: "For a bundle/membership, measure the flywheel: retention × spend, powered by benefit engagement. Single-perk metrics miss the point of the bundle entirely." }
    ]
  },
  {
    slug: "pinterest-pin", company: "Pinterest", wordmark: "Pinterest", brand: "#e60023", readTime: "8 min read",
    title: "As PM for Pinterest's Pin feature, what metrics prove its effectiveness?",
    body: [
      { t: "p", x: "A Pin is Pinterest's atom — save an idea, get inspired, act on it. Measuring its effectiveness means asking: are Pins being saved, rediscovered, and turned into action? Let's trace the idea from save to action." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Pins let users save and organise images/ideas onto boards, and discover more like them. The job: fuel inspiration that leads to action — clicking through, buying, or creating." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Actioned Pins — saved Pins that lead to a meaningful action (click-through to source, purchase, or re-engagement). It ties the feature to outcomes, not just hoarding." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Creation & saving" },
      { t: "ul", items: ["Pins saved per user; boards created.", "Save rate on impressions (are Pins compelling?)."] },
      { t: "sub", x: "Discovery & relevance" },
      { t: "ul", items: ["Click-through rate on Pins and related Pins.", "Search → Pin engagement.", "Relevance of recommended Pins."] },
      { t: "sub", x: "Action & outcomes" },
      { t: "ul", items: ["Outbound click-through to source sites.", "Purchases from shoppable Pins.", "Re-pin / share rate (spread)."] },
      { t: "sub", x: "Retention" },
      { t: "ul", items: ["Return rate of active pinners.", "DAU/MAU stickiness."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Saves that never get revisited (the idea graveyard).", "Broken/dead Pin links.", "Spam and low-quality Pins.", "Advertiser vs. user-experience balance."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = Pins saved, rediscovered, and acted on — clicks and purchases rising alongside saves. A billion saves nobody revisits is inspiration going to waste." },
      { t: "p", x: "For discovery/save products (Pinterest, Netflix My List), always follow the save to the ACTION. Saving is intent; action is value." }
    ]
  },
  {
    slug: "ms-teams", company: "Microsoft Teams", wordmark: "Teams", brand: "#4b53bc", readTime: "8 min read",
    title: "How would you measure the success of Microsoft Teams' collaboration tools?",
    body: [
      { t: "p", x: "Teams is a workplace hub — chat, calls, files, meetings. 'Measure success' here means measuring whether teams genuinely run their day inside it, across multiple tools — not just show up for a scheduled call." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Teams bundles chat, video meetings, file collaboration and app integrations for the workplace. The job: become the daily operating system for how a team communicates and gets work done." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Weekly active teams using multiple collaboration modes — teams where members chat, meet AND collaborate on files regularly. Depth of adoption across tools, not a single feature's usage." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Adoption breadth" },
      { t: "ul", items: ["% of members active weekly per team.", "Number of collaboration modes used (chat + meetings + files).", "Channels and teams created."] },
      { t: "sub", x: "Engagement" },
      { t: "ul", items: ["Messages sent/read; meetings hosted and attended.", "Files co-edited; app integrations connected.", "Meeting features used (share, record, breakouts)."] },
      { t: "sub", x: "Retention" },
      { t: "ul", items: ["Team-level weekly retention.", "Cross-tool stickiness (do they use more over time?)."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Notification overload and mute rates.", "Meeting fatigue.", "Support tickets and onboarding friction.", "Single-feature-only teams (shallow-adoption risk)."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = teams adopting Teams broadly and repeatedly — chatting, meeting and co-creating — not just dialing into scheduled calls. Breadth and repetition are the real signals of a workplace hub winning." },
      { t: "p", x: "For a suite product, measure breadth of adoption at the team level. One feature used by a few isn't success; the whole team living inside it is." }
    ]
  },
  {
    slug: "twitter-retweet", company: "Twitter", wordmark: "Twitter", brand: "#1da1f2", readTime: "8 min read",
    title: "How would you measure the success of Twitter's Retweet feature?",
    body: [
      { t: "p", x: "The Retweet is a pure amplification engine — it exists to spread ideas across the network. So success is about reach and healthy virality, watched carefully so 'spread' doesn't become 'spread of garbage.' Let's measure it responsibly." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Retweet lets users rebroadcast a tweet to their followers instantly. The job: amplify content and conversation across the network, keeping the platform lively and connected." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Incremental reach and engagement generated by Retweets — the extra impressions and interactions a tweet earns because it was retweeted. It captures the feature's amplification job directly." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Usage" },
      { t: "ul", items: ["Retweets per active user; % of users who retweet.", "Retweets per tweet (spread factor).", "Quote-tweet vs. plain-retweet split."] },
      { t: "sub", x: "Amplification & reach" },
      { t: "ul", items: ["Additional impressions per retweet.", "Cascade depth — retweets of retweets.", "New engagement (replies, likes, follows) driven by retweets."] },
      { t: "sub", x: "Network health" },
      { t: "ul", items: ["Return rate of users who retweet or are retweeted.", "Follower growth attributable to retweets."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Misinformation / harmful content spread (amplification's dark side).", "Ratio of low-quality or spam retweets.", "Report and mute rates on retweeted content."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = Retweets driving real incremental reach and healthy conversation — while the guardrails keep amplification from turbo-charging spam or misinformation. Virality is only a win if what goes viral is worth spreading." },
      { t: "p", x: "For amplification/virality features, measure the reach they create AND guard hard against what that reach can amplify. Responsible virality is the whole job." }
    ]
  },
  {
    slug: "google-maps", company: "Google Maps", wordmark: "Maps", brand: "#34a853", readTime: "8 min read",
    title: "How would you measure the success of Google Maps' route-planning feature?",
    body: [
      { t: "p", x: "Route planning has a brutally honest success test: did the user get where they were going, quickly and correctly, and trust it enough to use it again? Accuracy is everything here — one wrong turn destroys trust instantly." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Route planning gives users the best way from A to B — fast, accurate, multi-modal. The job: reliable navigation people trust for every trip." },
      { t: "journey", label: "User journey", steps: ["Enter destination", "See route options", "Pick a route", "Navigate turn-by-turn", "Arrive"] },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Successfully completed navigations — trips where the user follows a route to arrival. It proves the core job: got them there, reliably." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Usage & conversion" },
      { t: "ul", items: ["Route searches; search → navigation-start rate.", "Trips navigated per user."] },
      { t: "sub", x: "Quality & accuracy" },
      { t: "ul", items: ["ETA accuracy (predicted vs. actual).", "Reroute rate mid-trip (a signal of bad initial routing).", "Route-abandonment or manual-deviation rate."] },
      { t: "sub", x: "Breadth & retention" },
      { t: "ul", items: ["Multi-modal usage (drive, transit, walk, cycle).", "Return rate for navigation.", "Saved places and repeat trips."] },
      { t: "step", label: "STEP 4", x: "Guardrails" },
      { t: "ul", items: ["Wrong or unsafe routing incidents.", "Stale data (closed roads, bad traffic).", "Battery/performance during navigation.", "User-reported errors."] },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = more trips completed with accurate ETAs and few reroutes, across modes, with users returning. A pretty map that sends you the wrong way fails the only test that matters." },
      { t: "p", x: "For utility features, accuracy and completion ARE the product. Measure whether the job got done right, and guard obsessively against errors that break trust." }
    ]
  },
  {
    slug: "google-search", company: "Google", wordmark: "Google", brand: "#4285f4", readTime: "9 min read",
    title: "As PM for Google Search, what metrics prove its effectiveness?",
    body: [
      { t: "p", x: "Search is the ultimate 'did we answer the question?' product. Measuring it means measuring whether users find what they need, fast — and crucially, reading the signals that reveal satisfaction vs. frustration. This one's a masterclass in metric nuance." },
      { t: "step", label: "STEP 1", x: "What is it for?" },
      { t: "p", x: "Google Search takes a query and returns the most relevant, trustworthy results, instantly. The job: satisfy the user's intent as fast as possible — ideally on the first try." },
      { t: "step", label: "STEP 2", x: "The North Star" },
      { t: "callout", label: "North Star", x: "Successful searches — sessions where the user finds what they need and their intent is satisfied (often a 'good click' with long dwell, or a satisfied no-click answer). Relevance that resolves intent, not raw query volume." },
      { t: "step", label: "STEP 3", x: "Input metrics" },
      { t: "sub", x: "Relevance & success signals" },
      { t: "ul", items: ["Click-through rate on top results.", "'Good clicks' — clicks with long dwell time (they found it).", "Query success rate; answers resolved without a second query."] },
      { t: "sub", x: "Effort & speed" },
      { t: "ul", items: ["Time to first click / to answer.", "Query reformulation rate (reformulating = we missed).", "Results-page latency."] },
      { t: "sub", x: "Engagement & retention" },
      { t: "ul", items: ["Searches per user; return rate.", "Featured-snippet / instant-answer satisfaction."] },
      { t: "step", label: "STEP 4", x: "Guardrails — reading the signals carefully" },
      { t: "ul", items: ["Pogo-sticking — click a result, bounce back fast, click another (dissatisfaction hiding inside a 'click').", "Short clicks and high reformulation (we didn't answer).", "Misinformation or low-quality results surfaced.", "Over-serving ads at the cost of relevance."] },
      { t: "note", x: "The subtle bit: a click is NOT automatically success. A user who clicks, hates it, and comes back to search again looks 'engaged' but was failed. Great search PMs measure satisfied clicks, not clicks. That distinction is the whole game." },
      { t: "step", label: "STEP 5", x: "How I'd call it a win" },
      { t: "p", x: "Success = more intents satisfied fast — good clicks and instant answers up, reformulation and pogo-sticking down. Engagement that reflects finding, not floundering." },
      { t: "p", x: "For search and Q&A products, the art is separating satisfaction from mere activity. Learn to read good clicks vs. pogo-sticking and you'll measure what actually matters." }
    ]
  }
];
