// PM Roadmap — the full roadmap.sh Product Manager path, every node, with detailed explanations in Shubham's voice.
// Rendered on Zero-to-PM.dc.html. Read-state + bookmarks persist in localStorage.
window.PM_ROADMAP = [
  { sec: "Getting Started", accent: "#5b2fe0", nodes: [
    { id: "what-is-pm", t: "What is Product Management?", body: "Product management is the craft of deciding what to build, for whom, and why — then rallying design, engineering and the business to make it real. A PM sits at the intersection of business viability, customer value, design usability and engineering feasibility, and owns the outcome, not the output. You don't need a title to start thinking this way — start today, with any product you use." },
    { id: "pm-vs-project", t: "Product vs Project Management", body: "A product manager owns the 'what' and 'why' — the problem, the outcome, the long-lived product. A project manager owns the 'how' and 'when' — timelines, resources, delivery of a defined scope. PMs optimise for value delivered; project managers optimise for on-time, on-budget execution. Great products often need both, working hand in hand." },
    { id: "roles", t: "Roles & Responsibilities", body: "Discovery (finding the right problems), strategy (choosing where to play), prioritisation (deciding what's next), execution (shipping with the team), and communication (aligning everyone). Day to day you'll write specs, talk to users, wrangle data, unblock engineers and manage stakeholders. It's a generalist role — breadth over depth — and that's exactly what makes it fun." },
    { id: "key-skills", t: "Key Skills", body: "Communication, prioritisation, user empathy, data fluency, and influence-without-authority top the list, wrapped in strong product sense and structured thinking. Technical and design literacy help you earn trust with your team. Every one of these is learnable with reps — nobody is born a PM." }
  ]},
  { sec: "Product Development Lifecycle", accent: "#ff5a3c", nodes: [
    { id: "lc-intro", t: "Introduction", body: "Every product moves through a lifecycle — introduction, growth, maturity, decline — and your job as PM shifts at each stage. Knowing which stage you're in tells you whether to chase adoption, defend share, or sunset gracefully. Read the stage first; then pick the play." },
    { id: "lc-dev", t: "Development", body: "The pre-launch stage: research, build and validate before the product hits the market. Costs are high, revenue is zero, and the goal is to prove the problem and the solution are real. Move fast on learning, slow on scaling." },
    { id: "lc-growth", t: "Growth", body: "Adoption accelerates, revenue climbs, and competitors notice. Focus shifts to scaling acquisition, strengthening retention and widening the moat. Guard against growing so fast that quality and unit economics slip." },
    { id: "lc-maturity", t: "Maturity", body: "Growth flattens as the market saturates. Now you defend share, squeeze efficiency, and find new segments or use cases to extend the curve. This is where disciplined optimisation quietly pays off." },
    { id: "lc-decline", t: "Decline", body: "Demand falls as tastes shift or better alternatives arrive. Decide deliberately: revive with a pivot, harvest the remaining value, or retire with dignity. A graceful sunset is a real PM skill, not a failure." }
  ]},
  { sec: "Idea Generation", accent: "#c6f24e", nodes: [
    { id: "mind-mapping", t: "Mind Mapping", body: "A visual way to explode a central problem into branches of related ideas, revealing connections you'd miss in a list. Great for early, divergent thinking. Start messy — structure comes later." },
    { id: "brainwriting", t: "Brainwriting", body: "Everyone writes ideas silently before sharing, so the loudest voice doesn't dominate. It surfaces more, and more diverse, ideas than open brainstorms. Perfect for balanced teams." },
    { id: "scamper", t: "SCAMPER", body: "A prompt checklist — Substitute, Combine, Adapt, Modify, Put to another use, Eliminate, Reverse — to force fresh angles on an existing product or idea. It's creativity on rails when you're stuck." },
    { id: "brainstorming", t: "Brainstorming Techniques", body: "Structured group ideation: set a clear question, defer judgement, aim for quantity, then converge. The magic is separating idea generation from idea evaluation — never do both at once." },
    { id: "discovery", t: "Discovery", body: "The stage of exploring problems and opportunities before committing to solutions. You're reducing uncertainty — talking to users, testing assumptions, spotting real pains. Fall in love with the problem, not your first idea." },
    { id: "selection", t: "Selection", body: "Choosing which ideas or opportunities are worth pursuing, using impact, effort, strategic fit and confidence. Saying no to good ideas to protect the great ones is the heart of the job." },
    { id: "validation", t: "Validation", body: "Testing whether an idea actually solves the problem before you build it fully — via prototypes, experiments, landing pages or interviews. Cheap validation beats expensive regret every time." },
    { id: "iterative", t: "Iterative Process", body: "Build → measure → learn → repeat. Ship small, learn fast, and let real feedback shape the next loop rather than a giant upfront plan. Progress compounds through iteration." },
    { id: "execution", t: "Execution", body: "Turning a chosen, validated idea into a shipped reality with the team — scoping, sequencing and unblocking. Ideas are cheap; disciplined execution is the rare, valuable part." },
    { id: "blue-ocean", t: "Blue Ocean Strategy", body: "Instead of fighting rivals in a bloody 'red ocean', create uncontested 'blue ocean' market space by redefining value. Compete less, create more. Ask: what can we make irrelevant, and what can we invent?" },
    { id: "triz", t: "TRIZ", body: "The Theory of Inventive Problem Solving — a systematic method that studies patterns in past inventions to resolve contradictions creatively. It turns 'we're stuck' into 'here's a structured way through'." },
    { id: "problem-framing", t: "Problem Framing", body: "Defining the real problem before jumping to solutions — sharp, specific, and centred on the user. A well-framed problem is half-solved; a vague one wastes months. Reframe until it's crisp." }
  ]},
  { sec: "Market & User Research", accent: "#5b2fe0", nodes: [
    { id: "product-identification", t: "Product Identification", body: "Spotting the product or opportunity worth pursuing by matching a real market need to something you can build and win at. It's where market signals meet your team's strengths." },
    { id: "market-analysis", t: "Market Analysis", body: "Sizing and understanding the market — demand, growth, dynamics, TAM/SAM/SOM — to judge whether an opportunity is big enough to matter. Numbers ground your ambition in reality." },
    { id: "identifying-needs", t: "Identifying Market Needs", body: "Uncovering the unmet, underserved or badly-served needs in a market through research and observation. The biggest opportunities hide in the pains people have stopped complaining about because they assume nothing can change." },
    { id: "competitive-analysis", t: "Competitive Analysis", body: "Studying rivals — their strengths, gaps, positioning and moves — to find where you can differentiate. Know the field before you pick your play. Their weaknesses are often your opening." },
    { id: "emerging-trends", t: "Emerging Market Trends", body: "Tracking shifts in technology, behaviour and regulation that will reshape your market. Skating to where the puck is going beats chasing where it's been. Curiosity is your edge here." },
    { id: "user-research", t: "User Research", body: "Systematically learning who your users are, what they need and how they behave — the foundation of every good product decision. When in doubt, talk to users; the answer is usually with them, not in a meeting." },
    { id: "user-personas", t: "User Personas", body: "Composite profiles of your key user types — goals, pains, context — that keep the whole team designing for real humans, not a faceless 'average user'. Specific beats generic every time." },
    { id: "user-interviews", t: "User Interviews", body: "One-on-one conversations to understand needs, motivations and frustrations deeply. Ask open questions, listen more than you talk, and dig into stories, not opinions. The gold is in the 'why'." },
    { id: "surveys", t: "Surveys & Questionnaires", body: "Structured questions at scale to quantify what interviews reveal qualitatively. Great for measuring how widespread a pattern is — but only as good as the questions you write. Pair them with interviews for depth plus breadth." },
    { id: "ethnographic", t: "Ethnographic Research", body: "Observing users in their real environment to see what they do, not just what they say. Behaviour beats stated intent — people are unreliable narrators of their own habits. Watch, and you'll learn what surveys never surface." },
    { id: "positioning", t: "Positioning", body: "Defining how your product should live in the customer's mind relative to alternatives. Clear positioning makes marketing, sales and design decisions obvious. Own a space; don't blur into everyone else." },
    { id: "usp", t: "USP (Unique Selling Point)", body: "The one sharp reason customers should choose you over anything else. If you can't say it in a sentence, you haven't found it yet. Sharpen it until it's undeniable." },
    { id: "defining-communicating", t: "Defining & Communicating", body: "Articulating your positioning and USP so clearly that customers, partners and your own team all repeat it the same way. Alignment starts with words everyone shares." },
    { id: "market-segmentation", t: "Market Segmentation", body: "Splitting a broad market into groups with shared needs so you can target the ones you can serve best. Serve one segment brilliantly before trying to serve all." },
    { id: "case-studies", t: "Case Studies", body: "Real, documented stories of how customers use and benefit from a product — powerful proof for positioning and sales. Nothing persuades like a concrete win." }
  ]},
  { sec: "Product Strategy", accent: "#2f9e44", nodes: [
    { id: "vision-mission", t: "Vision & Mission Statement", body: "The vision is the future you're trying to create; the mission is how you'll pursue it day to day. Together they're the north star that keeps a team aligned when trade-offs get hard. A great vision is ambitious enough to be scary and clear enough to act on." },
    { id: "vm-proposition", t: "Proposition", body: "The core promise of value your product makes to customers — the essence of why it deserves to exist. Everything you build should ladder up to it." },
    { id: "vm-capabilities", t: "Capabilities", body: "The strengths and assets — tech, talent, data, distribution — that let you deliver your vision better than others. Strategy means betting on your real capabilities." },
    { id: "vm-solved-constraints", t: "Solved Constraints", body: "The limitations you've already overcome that unlock new possibilities. Naming them reminds the team how far the ground has shifted in your favour." },
    { id: "vm-future-constraints", t: "Future Constraints", body: "The limits you'll hit next — technical, market or resource — so you can plan around them proactively instead of being ambushed. Anticipation is a strategic advantage." },
    { id: "vm-reference", t: "Reference Materials", body: "The research, data and artefacts that ground your strategy in evidence rather than opinion. Keep the receipts; they win debates." },
    { id: "vm-narrative", t: "Narrative", body: "The compelling story that ties vision, mission and strategy into something people feel and remember. Humans follow stories, not spreadsheets — learn to tell yours." },
    { id: "defining-goals", t: "Defining Goals", body: "Turning strategy into concrete, measurable targets so progress is unambiguous. Good goals are specific, time-bound and tied to outcomes, not activity. What gets measured gets managed." },
    { id: "goal-target", t: "Target", body: "The specific number or state you're aiming to reach. A goal without a target is just a wish — give it an edge." },
    { id: "goal-baseline", t: "Baseline", body: "Where you're starting from, so you can measure real movement. Never set a target without knowing your baseline." },
    { id: "goal-trend", t: "Trend", body: "The direction and pace of change over time — is the metric already climbing, flat, or falling? Context turns a number into a story." },
    { id: "goal-timeframe", t: "Timeframe", body: "The window in which you'll hit the target. Timeframes create urgency and make success or failure legible." },
    { id: "goal-types", t: "Goal Types", body: "From north-star and OKRs to input vs. output goals — choosing the right kind of goal shapes team behaviour. Reward outcomes, not just effort." },
    { id: "value-proposition", t: "Value Proposition", body: "A crisp statement of the value customers get, for whom, and why it beats alternatives. It's the bridge between what you build and why anyone cares." },
    { id: "vp-canvas", t: "Value Proposition Canvas", body: "A tool that maps customer jobs, pains and gains against your product's pain-relievers and gain-creators. It forces a tight fit between what users need and what you offer." },
    { id: "value-vs-features", t: "Value vs Features", body: "Customers buy outcomes, not feature lists. Always translate what you build into the value it creates — a feature nobody values is just cost. Lead with the 'so what'." },
    { id: "finding-balance", t: "Finding Balance", body: "Balancing enough features to deliver value against the simplicity that keeps a product usable and focused. More isn't better; right is better." },
    { id: "feature-creep", t: "Feature Creep", body: "The slow bloat of adding features until the product becomes complex and unfocused. Guard the roadmap fiercely — every yes is a no to something else, and to simplicity." },
    { id: "strategic-thinking", t: "Strategic Thinking", body: "Seeing the whole board — market, competitors, capabilities, timing — and choosing where to play and how to win. Zoom out regularly; it's easy to get lost in the backlog." },
    { id: "competitive-strategy", t: "Competitive Strategy", body: "Your deliberate plan to win against alternatives — through differentiation, cost, focus or speed. Decide how you'll win before you start playing." },
    { id: "five-forces", t: "Five Forces Analysis", body: "Porter's framework — rivalry, new entrants, substitutes, supplier power, buyer power — to judge an industry's attractiveness and your leverage in it. It reveals where the profit and the pressure really sit." },
    { id: "competitive-advantage", t: "Competitive Advantage", body: "The durable edge that lets you outperform rivals over time — network effects, brand, tech, scale or data. Chase advantages that compound and are hard to copy." },
    { id: "strategic-partners", t: "Strategic Partners", body: "Other organisations whose strengths complement yours, unlocking reach or capability you couldn't build alone. The right partnership is a shortcut; the wrong one is a distraction." },
    { id: "identify-partners", t: "Identify Partners", body: "Finding the partners whose goals align with yours and whose strengths fill your gaps. Fit and shared incentives matter more than size." },
    { id: "managing-partnerships", t: "Managing Partnerships", body: "Keeping partnerships healthy through clear expectations, communication and mutual value. A partnership is a relationship, not a contract — tend it." }
  ]},
  { sec: "Product Planning", accent: "#ff5a3c", nodes: [
    { id: "product-requirements", t: "Product Requirements", body: "The clear definition of what needs to be built and why, so the team can execute without guessing. Good requirements describe the problem and outcome, leaving room for the team to find the best solution." },
    { id: "writing-prds", t: "Writing PRDs", body: "A Product Requirements Document captures the problem, goals, users, scope and success metrics in one shared source of truth. Write for clarity, not length — a great PRD aligns everyone in a single read." },
    { id: "user-stories", t: "User Stories", body: "Short, user-centred descriptions of a need in the form 'As a [user], I want [goal] so that [benefit]'. They keep the team building for people, not tickets." },
    { id: "job-stories", t: "Job Stories", body: "An alternative framing — 'When [situation], I want to [motivation], so I can [outcome]' — that emphasises context over persona. Great when the situation matters more than who the user is." },
    { id: "product-roadmap", t: "Product Roadmap", body: "A living plan of what you'll pursue and roughly when, tying day-to-day work to strategy. It's a communication tool, not a promise carved in stone — expect it to evolve." },
    { id: "creating-roadmap", t: "Creating a Roadmap", body: "Translating strategy and priorities into themes and sequenced bets. Anchor it on outcomes and problems, not a wishlist of features." },
    { id: "prioritising-features", t: "Prioritising Features", body: "Deciding what to build next using impact, effort, confidence and strategic fit (RICE, MoSCoW, and friends). Prioritisation is the job — say no with reasons." },
    { id: "continuous-roadmapping", t: "Continuous Roadmapping", body: "Treating the roadmap as an always-updating living document rather than an annual ritual. Revisit it as you learn; rigidity is the enemy of relevance." },
    { id: "outcome-roadmaps", t: "Outcome-Based Roadmaps", body: "Organising the roadmap around outcomes (e.g., 'improve activation') instead of a fixed feature list. It gives teams the freedom to find the best solution and keeps focus on impact." },
    { id: "communicating-roadmap", t: "Communicating the Roadmap", body: "Sharing the plan so every stakeholder understands the what, why and rough when — and stays aligned as it changes. Over-communicate; assumptions fill silence." },
    { id: "backlog-management", t: "Backlog Management", body: "Keeping the list of potential work healthy, prioritised and understandable so the team always knows what's next. A tidy backlog is a calm team." },
    { id: "prioritization-techniques", t: "Prioritization Techniques", body: "Methods like RICE, MoSCoW, Kano and value-vs-effort that turn gut feel into defensible decisions. Pick one, apply it consistently, and show your reasoning." },
    { id: "grooming-sessions", t: "Grooming Sessions", body: "Regular reviews to refine, estimate and prioritise backlog items so they're ready for the team to pick up. A little grooming prevents a lot of sprint chaos." },
    { id: "user-story-mapping", t: "User Story Mapping", body: "A visual technique that arranges stories along the user's journey to reveal gaps and plan releases. It keeps the whole experience in view, not just isolated features." }
  ]},
  { sec: "Product Design", accent: "#c6f24e", nodes: [
    { id: "ux-ui", t: "UX / UI Design", body: "UX is how it works and feels; UI is how it looks. As a PM you don't have to be a designer, but you must have taste and empathy to partner well and protect the user experience." },
    { id: "ux-principles", t: "Principles of UX Design", body: "Clarity, consistency, feedback, error prevention and accessibility — the fundamentals that make products feel effortless. Learn them and you'll spot friction everywhere." },
    { id: "wireframing", t: "Wireframing & Prototyping", body: "Low- and high-fidelity mockups that let you test ideas before building them for real. Cheap to change, priceless for aligning the team and catching problems early." },
    { id: "design-thinking", t: "Design Thinking", body: "A human-centred process — empathise, define, ideate, prototype, test — for solving problems creatively. It keeps the user at the centre of every decision." },
    { id: "service-design", t: "Service Design", body: "Designing the whole end-to-end experience across touchpoints, not just a single screen. Great products often live inside a larger service — design the journey, not just the app." },
    { id: "interaction-design", t: "Interaction Design", body: "Crafting how users act and the product responds — flows, states, micro-interactions and feedback. Good interaction design makes complex things feel simple." },
    { id: "user-testing", t: "User Testing", body: "Watching real users attempt real tasks to find where they struggle. There's no substitute for seeing someone use your product — it's humbling and clarifying." },
    { id: "usability-testing", t: "Usability Testing", body: "Structured sessions measuring how easily users complete key tasks. Small samples reveal most issues — test early, test often, fix fast." },
    { id: "ab-testing-design", t: "A/B Testing", body: "Comparing two versions with live users to see which performs better on a metric. It replaces opinion with evidence — but respect sample sizes and significance." },
    { id: "remote-user-testing", t: "Remote User Testing", body: "Testing with users wherever they are, moderated or unmoderated, via tools that record their sessions. It widens your reach and speeds up learning." }
  ]},
  { sec: "Development & Launch", accent: "#5b2fe0", nodes: [
    { id: "agile", t: "Agile Methodology", body: "An iterative, adaptive way of building — short cycles, frequent delivery, and responding to change over rigid plans. It's a mindset as much as a process: learn fast, adjust often." },
    { id: "scrum", t: "Scrum Basics", body: "A framework of sprints, roles (PO, Scrum Master, team) and ceremonies that delivers work in short, inspectable increments. Structure that keeps teams shipping and learning." },
    { id: "kanban", t: "Kanban Basics", body: "A flow-based method visualising work on a board and limiting work-in-progress to keep things moving. Great when priorities shift often and continuously." },
    { id: "sprint-planning", t: "Sprint Planning", body: "The session where the team commits to what it can deliver in the next sprint and how. Clear goals in, realistic commitments out." },
    { id: "standups", t: "Daily Standups", body: "A short daily sync on progress, plans and blockers. Keep it tight — it's for surfacing problems, not solving them in the meeting." },
    { id: "retrospectives", t: "Retrospectives", body: "A regular look back at what went well and what to improve, turning experience into better process. Continuous improvement is a team habit, not an event." },
    { id: "working-with-eng", t: "Working with Engineering Teams", body: "Building trust with engineers by bringing clear problems, honest constraints and shared ownership — never dictating solutions. Respect their craft and they'll go to war for the product with you." },
    { id: "mvp", t: "Minimum Viable Product (MVP)", body: "The smallest version that delivers real value and tests your core assumption with real users. Ship to learn, not to impress — the MVP is an experiment, not a mini-launch." },
    { id: "gtm", t: "Go-to-Market Strategy", body: "The plan for how you'll launch, reach and win customers — positioning, channels, pricing and messaging. A great product with no GTM is a secret." },
    { id: "launch-planning", t: "Launch Planning", body: "Coordinating everything — engineering, marketing, support, sales — so a release lands smoothly. Checklists and clear owners turn chaos into a confident launch." },
    { id: "marketing-strategies", t: "Marketing Strategies", body: "How you create awareness and demand — content, performance, community, PR and more. As PM you don't run all of it, but you must align product and message." },
    { id: "growth-hacking", t: "Growth Hacking", body: "Rapid, experiment-driven tactics to accelerate acquisition, activation and retention. Test cheap and fast; double down on what compounds." },
    { id: "release-strategies", t: "Release Strategies", body: "How you roll changes out — all at once, gradually, or hidden behind flags — to balance speed and safety. Ship smart, not just fast." },
    { id: "feature-toggles", t: "Feature Toggles", body: "Switches that turn features on or off without redeploying — enabling gradual rollout, testing and quick rollback. Your safety net for shipping bravely." },
    { id: "phased-rollouts", t: "Phased Rollouts", body: "Releasing to a small percentage of users first, then widening as confidence grows. Catch problems while they're small and contained." },
    { id: "dark-launches", t: "Dark Launches", body: "Releasing functionality invisibly to test performance and behaviour before revealing it to users. It de-risks big changes by testing in production quietly." }
  ]},
  { sec: "Product Metrics", accent: "#2f9e44", nodes: [
    { id: "key-metrics", t: "Key Product Metrics", body: "The numbers that tell you if the product is working — activation, engagement, retention, revenue. Choose a vital few and resist vanity metrics that feel good but mean little." },
    { id: "dau", t: "DAU (Daily Active Users)", body: "The count of unique users engaging each day — a pulse-check on daily habit and stickiness. Powerful for daily-use products, less so for occasional ones." },
    { id: "mau", t: "MAU (Monthly Active Users)", body: "Unique users active over a month — a broader measure of reach and overall engagement. Pair with DAU (DAU/MAU) to gauge stickiness." },
    { id: "conversion-rate", t: "Conversion Rate", body: "The percentage of users who take a desired action — sign up, buy, upgrade. It shows how well your funnel turns intent into outcome; small lifts compound hugely." },
    { id: "retention-rate", t: "Retention Rate", body: "The share of users who keep coming back over time — the truest signal of real value. Growth leaks out of a leaky bucket; retention is the bucket." },
    { id: "churn-rate", t: "Churn Rate", body: "The percentage of users or revenue lost in a period — retention's mirror. High churn means the product isn't delivering lasting value; chase the why." },
    { id: "ltv", t: "LTV (Lifetime Value)", body: "The total value a customer brings over their whole relationship with you. It sets the ceiling on what you can spend to acquire and keep them." },
    { id: "cac", t: "CAC (Customer Acquisition Cost)", body: "What it costs, all-in, to win one new customer. A healthy business needs LTV comfortably above CAC — the ratio is a north star for sustainable growth." },
    { id: "north-star", t: "North Star Metric", body: "The single metric that best captures the core value your product delivers, aligning the whole team. Choose it carefully — it quietly shapes every decision downstream." },
    { id: "data-driven", t: "Data-Driven Decision Making", body: "Using evidence — not the loudest opinion — to decide. Balance quantitative data with qualitative insight; numbers tell you what, users tell you why." },
    { id: "ab-testing-metrics", t: "A/B Testing", body: "Running controlled experiments to measure the true impact of a change before rolling it out. Trust tested results over hunches — but mind statistical significance." },
    { id: "cohort-analysis", t: "Cohort Analysis", body: "Grouping users by a shared trait or start date to see how behaviour evolves over time. It reveals whether your product is genuinely improving for new users." },
    { id: "predictive-analytics", t: "Predictive Analytics", body: "Using historical data and models to forecast future behaviour like churn or demand. It helps you act before problems arrive rather than after." },
    { id: "feedback-loops", t: "Feedback Loops", body: "Systems that continuously feed user signals back into the product so it keeps improving. The tighter the loop, the faster you learn." }
  ]},
  { sec: "Stakeholder Management", accent: "#ff5a3c", nodes: [
    { id: "communication-skills", t: "Communication Skills", body: "The PM's superpower — translating between users, business, design and engineering so everyone rows the same way. Clarity, brevity and empathy carry you further than any framework." },
    { id: "communication-techniques", t: "Communication Techniques", body: "Tailoring your message to the audience — executives want outcomes, engineers want context, users want empathy. Say the right thing, the right way, to the right room." },
    { id: "difficult-conversations", t: "Difficult Conversations", body: "Handling disagreement, bad news and pushback with honesty and respect. Address issues early and directly — avoidance is the expensive option." },
    { id: "active-listening", t: "Active Listening", body: "Truly hearing people — reflecting back, asking, withholding judgement — so they feel understood and you learn what's really going on. Listen to understand, not to reply." },
    { id: "conflict-resolution", t: "Conflict Resolution", body: "Turning tension into progress by finding shared goals beneath opposing positions. Attack the problem, not the person, and aim for the outcome, not the win." },
    { id: "alignment-buyin", t: "Alignment & Buy-In", body: "Getting stakeholders to genuinely support a direction, not just tolerate it. Involve people early — buy-in is built, not announced." },
    { id: "showing-impact", t: "Showing Impact", body: "Demonstrating the value your work delivered, in terms each audience cares about. Impact you can't communicate is impact that goes unnoticed." },
    { id: "managing-stakeholders", t: "Managing Stakeholders", body: "Keeping everyone with a stake — leadership, customers, partners, teams — informed, aligned and appropriately involved. Manage expectations before they manage you." },
    { id: "identifying-stakeholders", t: "Identifying Stakeholders", body: "Mapping everyone affected by or influencing your product so no key voice is missed. A surprise stakeholder late in a project is a preventable crisis." },
    { id: "stakeholder-mapping", t: "Stakeholder Mapping", body: "Plotting stakeholders by influence and interest to decide how much to engage each. Focus energy where it moves the needle." },
    { id: "stakeholder-engagement", t: "Stakeholder Engagement", body: "The ongoing rhythm of updates, involvement and relationship-building that keeps stakeholders on side. Consistency beats occasional grand gestures." },
    { id: "remote-stakeholders", t: "Remote Stakeholders", body: "Keeping distant or distributed stakeholders as informed and aligned as those in the room. Be deliberate, written and inclusive across time zones." }
  ]},
  { sec: "Product Management Tools", accent: "#c6f24e", nodes: [
    { id: "roadmapping-tools", t: "Roadmapping Tools", body: "Software for building and sharing roadmaps and priorities with stakeholders. The tool matters less than the thinking — but a good one keeps everyone looking at the same plan." },
    { id: "product-board", t: "Productboard", body: "A popular tool for capturing feedback, prioritising features and building roadmaps around customer needs. Strong at connecting insight to plan." },
    { id: "aha", t: "Aha!", body: "A comprehensive roadmapping and strategy tool favoured by larger product orgs. Rich features for linking goals, initiatives and releases." },
    { id: "notion", t: "Notion", body: "A flexible workspace many PMs use for PRDs, notes, wikis and lightweight roadmaps. Great when you want one adaptable home for everything." },
    { id: "pm-tools", t: "Project Management Tools", body: "Software to plan, track and ship the actual work with your team. Where the roadmap meets reality, sprint by sprint." },
    { id: "jira", t: "Jira", body: "The industry-standard issue tracker for agile teams — sprints, boards, backlogs and reporting. Powerful and configurable, if sometimes heavy." },
    { id: "linear", t: "Linear", body: "A fast, keyboard-first issue tracker loved by modern software teams for its speed and simplicity. Increasingly the startup favourite." },
    { id: "trello", t: "Trello", body: "A simple, visual Kanban-board tool great for lightweight tracking and small teams. Easy to start, easy to love." },
    { id: "analytics-tools", t: "Analytics Tools", body: "Software to measure user behaviour and product performance. Data you can't see, you can't act on — instrument early." },
    { id: "amplitude", t: "Amplitude", body: "A product-analytics platform for understanding user behaviour, funnels and retention deeply. A PM favourite for behavioural insight." },
    { id: "heap", t: "Heap", body: "Analytics that auto-capture every user interaction, so you can analyse events retroactively without pre-tagging. Great for exploratory analysis." },
    { id: "looker", t: "Looker", body: "A business-intelligence platform for building dashboards and exploring data across the company. Strong for shared, governed metrics." },
    { id: "communication-tools", t: "Communication Tools", body: "Where your team talks, decides and stays aligned day to day. The nervous system of a distributed team." },
    { id: "slack", t: "Slack", body: "The widely-used team messaging hub — channels, DMs and integrations that centralise work chat. Powerful, if you tame the notifications." },
    { id: "teams", t: "Microsoft Teams", body: "Microsoft's chat, meeting and collaboration suite, common in enterprises tied to the Office ecosystem. Chat plus meetings plus files in one place." },
    { id: "discord", t: "Discord", body: "Community-first chat with servers, channels and voice — increasingly used by product communities and teams. Great for real-time, informal collaboration." }
  ]},
  { sec: "Risk Management", accent: "#5b2fe0", nodes: [
    { id: "identifying-risks", t: "Identifying Risks", body: "Spotting what could go wrong — technical, market, execution or external — before it does. Naming risks early is how you stay ahead of them instead of reacting." },
    { id: "risk-identification", t: "Risk Identification Techniques", body: "Methods like premortems, checklists and brainstorming to surface hidden risks. Imagine the failure, then work backward to prevent it." },
    { id: "risk-register", t: "Risk Register", body: "A living log of known risks, their likelihood, impact and owner. What's written down gets watched; what's in your head gets forgotten." },
    { id: "risk-assessment", t: "Risk Assessment", body: "Judging how likely each risk is and how bad it would be, so you prioritise attention. Not all risks deserve equal worry — triage them." },
    { id: "qualitative-risk", t: "Qualitative Risk Assessment", body: "Rating risks by descriptive levels (low/medium/high) when precise numbers aren't available. Fast, intuitive and good enough to act." },
    { id: "quantitative-risk", t: "Quantitative Risk Assessment", body: "Putting numbers — probabilities and costs — on risks for sharper prioritisation. Use it when the stakes justify the rigour." },
    { id: "risk-mitigation", t: "Risk Mitigation", body: "Taking action to reduce a risk's likelihood or impact before it strikes. Prevention is cheaper than the cure — plan it in." },
    { id: "mitigation-strategies", t: "Mitigation Strategies", body: "Avoid, reduce, transfer or accept — the four classic ways to handle a risk. Choose consciously for each; doing nothing is a choice too." },
    { id: "contingency-planning", t: "Contingency Planning", body: "Having a ready plan B for when a risk materialises anyway. Hope for the best, prepare for the rest." },
    { id: "monitoring-risks", t: "Monitoring & Controlling Risks", body: "Continuously watching known risks and scanning for new ones as things change. Risk management is ongoing, not a one-time checklist." },
    { id: "risk-monitoring-tools", t: "Risk Monitoring Tools", body: "Dashboards, alerts and registers that keep risks visible and tracked over time. Visibility is the first line of defence." },
    { id: "risk-audits", t: "Risk Audits", body: "Periodic reviews to check whether risks and mitigations are still accurate and effective. Reality drifts — audit to stay honest." }
  ]},
  { sec: "Advanced Topics", accent: "#2f9e44", nodes: [
    { id: "scaling-products", t: "Scaling Products", body: "Growing a product's users, markets and impact without breaking what made it work. Scaling multiplies both strengths and cracks — reinforce the foundations first." },
    { id: "growth-strategies", t: "Growth Strategies", body: "Deliberate plays — virality, partnerships, new segments, expansion revenue — to accelerate growth sustainably. Pick the engine that fits your product's nature." },
    { id: "internationalization", t: "Internationalization", body: "Adapting a product for new countries — language, currency, culture, regulation and local behaviour. Localisation is redesign, not translation." },
    { id: "platform-thinking", t: "Platform Thinking", body: "Building foundations others can build on, turning a product into an ecosystem with network effects. Platforms compound value as they grow." },
    { id: "portfolio-management", t: "Portfolio Management", body: "Managing multiple products or lines together, balancing investment across bets. Think like an investor allocating a finite budget for the biggest total return." },
    { id: "advanced-analysis", t: "Advanced Analysis", body: "Going beyond dashboards into modelling, prediction and machine-driven insight. Powerful leverage — but only when grounded in real questions." },
    { id: "predictive-analytics-adv", t: "Predictive Analytics", body: "Using models to anticipate outcomes — churn, demand, LTV — and act proactively. Forecasting turns hindsight into foresight." },
    { id: "ml-in-pm", t: "ML in Product Management", body: "Applying machine learning to power features (recommendations, ranking) and decisions. Know enough to scope it well and set realistic expectations with your team." },
    { id: "ai-in-pm", t: "AI in Product Management", body: "Using AI both inside products and in your own workflow — from copilots to automation. The PMs who master AI won't be replaced by it; they'll outrun those who don't." },
    { id: "leadership-influence", t: "Leadership & Influence", body: "Guiding people and outcomes without formal authority — through vision, trust and credibility. This is what separates a good PM from a great one." },
    { id: "building-teams", t: "Building & Leading Teams", body: "Creating high-trust, high-performing teams with clear purpose, autonomy and safety. Your job becomes making the team great, not being the hero." },
    { id: "influencing-authority", t: "Influencing without Authority", body: "PMs rarely 'manage' anyone — you lead through logic, empathy, data and relationships. Earn trust, share the why, and people follow willingly." },
    { id: "emotional-intelligence", t: "Emotional Intelligence", body: "Reading and managing emotions — yours and others' — to navigate people and pressure well. Often the real difference-maker when the work gets hard." }
  ]},
  { sec: "Keep Learning", accent: "#ff5a3c", nodes: [
    { id: "keep-learning", t: "Keep Learning", body: "Product management is a lifelong craft — the best PMs stay curious, read widely, ship, reflect and grow every single week. You've reached the end of the map, but never the end of the journey. Keep going — you've absolutely got this." },
    { id: "ux-roadmap", t: "UX Design Roadmap", body: "A related path worth exploring to deepen your design sense and partner better with designers. Adjacent skills make you a sharper PM." },
    { id: "data-analyst", t: "Data Analyst Roadmap", body: "A related path to strengthen your data fluency — SQL, analysis, visualisation. The more you can self-serve on data, the faster you decide." },
    { id: "design-system", t: "Design System", body: "A related topic — the shared library of components and standards that keeps products consistent and teams fast. Understanding it helps you scale quality." }
  ]}
];
